# EDA Framework

For future datasets, remember this sequence:

**Understand → Validate → Clean → Describe → Visualize → Compare → Investigate → Explain → Recommend**

A data analyst should not stop at *"sales decreased."* Continue asking:

**Where? → When? → Which segment/product/customer? → What variables are associated with it? → Is it an anomaly or recurring pattern? → What should the business investigate or do next?**

## Step 1 — Import libraries

In [3]:
import pandas as pd
import plotly.express as px

## Step 2 — Load the dataset

In [6]:
df= pd.read_csv('listings.csv')
df

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,958,https://www.airbnb.com/rooms/958,20260614073227,2026-06-14,city scrape,"Bright, Modern Garden Unit - 1BR/1BTH",**Please note that the house behind our backya...,NaN,https://a0.muscache.com/pictures/be1bf5ac-a955...,1169,...,4.90,4.97,4.78,STR-0006854,NaN,1,1,0,0,2.58
1,5858,https://www.airbnb.com/rooms/5858,20260614073227,2026-06-14,city scrape,Creative Sanctuary,We live in a large Victorian house on a quiet ...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,8904,...,4.85,4.77,4.68,NaN,NaN,1,1,0,0,0.50
2,8014,https://www.airbnb.com/rooms/8014,20260614073227,2026-06-14,city scrape,female HOST quiet fast internet market parking,Room is on the second floor so it gets a good ...,NaN,https://a0.muscache.com/pictures/2cc1fc3d-0ae0...,22402,...,4.95,4.60,4.67,STR-0000974,NaN,2,0,2,0,0.55
3,8142,https://www.airbnb.com/rooms/8142,20260614073227,2026-06-14,city scrape,*FriendlyRoom Apt. Style -UCSF/USF - San Franc...,Nice and good public transportation. 7 minute...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,21994,...,4.82,4.73,4.73,NaN,NaN,22,0,22,0,0.08
4,8339,https://www.airbnb.com/rooms/8339,20260614073227,2026-06-22,previous scrape,Historic Alamo Square Victorian,"For creative humans who love art, space, photo...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,24215,...,5.00,4.94,4.75,STR-0000264,NaN,1,1,0,0,0.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7327,1706112761356045678,https://www.airbnb.com/rooms/1706112761356045678,20260614073227,2026-06-14,city scrape,1 Bedroom in SF,This stylish and unique place sets the stage f...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,67057435,...,NaN,NaN,NaN,Exempt,NaN,1,0,1,0,NaN
7328,1706228944697932884,https://www.airbnb.com/rooms/1706228944697932884,20260614073227,2026-06-14,city scrape,A Tasteful and Elegant Home,"An elegant and comfortable home, thoughtfully ...",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,542901530,...,5.00,5.00,5.00,2026-004720STR,NaN,2,1,1,0,1.00
7329,1706229135493499688,https://www.airbnb.com/rooms/1706229135493499688,20260614073227,2026-06-14,city scrape,Luxury Modern Comfort Home,"Enjoy your own private lower-Level flat, thoug...",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,542901530,...,NaN,NaN,NaN,2026-004720STR,NaN,2,1,1,0,NaN
7330,1706477443981487094,https://www.airbnb.com/rooms/1706477443981487094,20260614073227,2026-06-14,city scrape,1BR Luxury Downtown | Bay Area,"A San Francisco landmark for over 70 years, th...",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,179605934,...,NaN,NaN,NaN,Exempt,NaN,2,1,1,0,NaN
7331,1706557052030067320,https://www.airbnb.com/rooms/1706557052030067320,20260614073227,2026-06-14,city scrape,Opera District Hotel | San Francisco,Soak up San Francisco’s dynamic arts culture a...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,179605934,...,NaN,NaN,NaN,Exempt,NaN,2,1,1,0,NaN


**Ask:** What does one row represent? How many records and columns do we have?

In [7]:
df.shape

(7332, 90)

## Step 3 — Understand structure and data types

**Ask:** Are numeric fields numeric? Is the date actually stored as a date?

In [8]:
import pandas as pd

df = pd.read_csv("listings.csv")

date_columns = [
    "last_scraped",
    "price_quote_checkin_date",
    "price_quote_checkout_date",
    "calendar_last_scraped",
    "first_review",
    "last_review"
]

for column in df.columns:
    if column in date_columns:
        continue

    text_values = (
        df[column]
        .astype("string")
        .str.strip()
        .replace(["", "Unknown", "None", "nan"], pd.NA)
        .str.replace(",", "", regex=False)
        .str.replace("$", "", regex=False)
    )

    numeric_values = pd.to_numeric(text_values, errors="coerce")

    valid_values = text_values.notna()

    # Convert only if every non-empty value is numeric
    if valid_values.any() and numeric_values[valid_values].notna().all():
        if (numeric_values[valid_values] % 1 == 0).all():
            df[column] = numeric_values.astype("Int64")
        else:
            df[column] = numeric_values.astype("Float64")

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7332 entries, 0 to 7331
Data columns (total 90 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            7332 non-null   Int64
 1   listing_url                                   7332 non-null   str
 2   scrape_id                                     7332 non-null   Int64
 3   last_scraped                                  7332 non-null   str
 4   source                                        7332 non-null   str
 5   name                                          7332 non-null   str
 6   description                                   7172 non-null   str
 7   neighborhood_overview                         0 non-null      float64
 8   picture_url                                   7332 non-null   str
 9   host_id                                       7332 non-null   Int64
 10  host_url                                      7332 non-null   str
 11  host_profile_id                               7242 non-null   Int64
 12  host_profile_url                              7239 non-null   str
 13  host_name                                     7242 non-null   str
 14  host_since                                    0 non-null      float64
 15  hosts_time_as_user_years                      7242 non-null   Int64
 16  hosts_time_as_user_months                     7242 non-null   Int64
 17  hosts_time_as_host_years                      7242 non-null   Int64
 18  hosts_time_as_host_months                     7242 non-null   Int64
 19  host_location                                 5670 non-null   str
 20  host_about                                    4452 non-null   str
 21  host_response_time                            0 non-null      float64
 22  host_response_rate                            0 non-null      float64
 23  host_acceptance_rate                          0 non-null      float64
 24  host_is_superhost                             7242 non-null   str
 25  host_thumbnail_url                            0 non-null      float64
 26  host_picture_url                              7242 non-null   str
 27  host_neighbourhood                            0 non-null      float64
 28  host_listings_count                           7242 non-null   Int64
 29  host_total_listings_count                     0 non-null      float64
 30  host_verifications                            0 non-null      float64
 31  host_has_profile_pic                          7242 non-null   str
 32  host_identity_verified                        7242 non-null   str
 33  neighbourhood                                 0 non-null      float64
 34  neighbourhood_cleansed                        7332 non-null   str
 35  neighbourhood_group_cleansed                  0 non-null      float64
 36  latitude                                      7332 non-null   Float64
 37  longitude                                     7332 non-null   Float64
 38  property_type                                 7332 non-null   str
 39  room_type                                     7332 non-null   str
 40  accommodates                                  7332 non-null   Int64
 41  bathrooms                                     5406 non-null   Float64
 42  bathrooms_text                                7252 non-null   str
 43  bedrooms                                      5341 non-null   Int64
 44  beds                                          5635 non-null   Int64
 45  amenities                                     7332 non-null   str
 46  price                                         5932 non-null   Float64
 47  price_quote_checkin_date                      6196 non-null   str
 48  price_quote_checkout_date                     6196 non-null   str
 49  price_quote_total_price                       5932 non-null   Float64
 50  price_quote_price_per_night                   5932 non-null   Float64
 51  price_quote_raw                               6196 non-null   str
 52  minimum_nights                                7328 non-null   Int64
 53  maximum_nights                                7328 non-null   Int64
 54  minimum_minimum_nights                        7328 non-null   Int64
 55  maximum_minimum_nights                        7328 non-null   Int64
 56  minimum_maximum_nights                        7328 non-null   Int64
 57  maximum_maximum_nights                        7328 non-null   Int64
 58  minimum_nights_avg_ntm                        7332 non-null   Float64
 59  maximum_nights_avg_ntm                        7332 non-null   Float64
 60  calendar_updated                              0 non-null      float64
 61  has_availability                              7281 non-null   str
 62  availability_30                               7332 non-null   Int64
 63  availability_60                               7332 non-null   Int64
 64  availability_90                               7332 non-null   Int64
 65  availability_365                              7332 non-null   Int64
 66  calendar_last_scraped                         7332 non-null   str
 67  number_of_reviews                             7332 non-null   Int64
 68  number_of_reviews_ltm                         7332 non-null   Int64
 69  number_of_reviews_l30d                        7332 non-null   Int64
 70  availability_eoy                              7332 non-null   Int64
 71  number_of_reviews_ly                          7332 non-null   Int64
 72  estimated_occupancy_l365d                     7332 non-null   Int64
 73  estimated_revenue_l365d                       5932 non-null   Int64
 74  first_review                                  5748 non-null   str
 75  last_review                                   5748 non-null   str
 76  review_scores_rating                          5748 non-null   Float64
 77  review_scores_accuracy                        5747 non-null   Float64
 78  review_scores_cleanliness                     5747 non-null   Float64
 79  review_scores_checkin                         5746 non-null   Float64
 80  review_scores_communication                   5747 non-null   Float64
 81  review_scores_location                        5746 non-null   Float64
 82  review_scores_value                           5746 non-null   Float64
 83  license                                       4860 non-null   str
 84  instant_bookable                              0 non-null      float64
 85  calculated_host_listings_count                7332 non-null   Int64
 86  calculated_host_listings_count_entire_homes   7332 non-null   Int64
 87  calculated_host_listings_count_private_rooms  7332 non-null   Int64
 88  calculated_host_listings_count_shared_rooms   7332 non-null   Int64
 89  reviews_per_month                             5748 non-null   Float64
dtypes: Float64(16), Int64(33), float64(13), str(28)
memory usage: 5.4 MB

In [9]:
df

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,958,https://www.airbnb.com/rooms/958,20260614073227,2026-06-14,city scrape,"Bright, Modern Garden Unit - 1BR/1BTH",**Please note that the house behind our backya...,NaN,https://a0.muscache.com/pictures/be1bf5ac-a955...,1169,...,4.9,4.97,4.78,STR-0006854,NaN,1,1,0,0,2.58
1,5858,https://www.airbnb.com/rooms/5858,20260614073227,2026-06-14,city scrape,Creative Sanctuary,We live in a large Victorian house on a quiet ...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,8904,...,4.85,4.77,4.68,NaN,NaN,1,1,0,0,0.5
2,8014,https://www.airbnb.com/rooms/8014,20260614073227,2026-06-14,city scrape,female HOST quiet fast internet market parking,Room is on the second floor so it gets a good ...,NaN,https://a0.muscache.com/pictures/2cc1fc3d-0ae0...,22402,...,4.95,4.6,4.67,STR-0000974,NaN,2,0,2,0,0.55
3,8142,https://www.airbnb.com/rooms/8142,20260614073227,2026-06-14,city scrape,*FriendlyRoom Apt. Style -UCSF/USF - San Franc...,Nice and good public transportation. 7 minute...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,21994,...,4.82,4.73,4.73,NaN,NaN,22,0,22,0,0.08
4,8339,https://www.airbnb.com/rooms/8339,20260614073227,2026-06-22,previous scrape,Historic Alamo Square Victorian,"For creative humans who love art, space, photo...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,24215,...,5.0,4.94,4.75,STR-0000264,NaN,1,1,0,0,0.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7327,1706112761356045678,https://www.airbnb.com/rooms/1706112761356045678,20260614073227,2026-06-14,city scrape,1 Bedroom in SF,This stylish and unique place sets the stage f...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,67057435,...,<NA>,<NA>,<NA>,Exempt,NaN,1,0,1,0,<NA>
7328,1706228944697932884,https://www.airbnb.com/rooms/1706228944697932884,20260614073227,2026-06-14,city scrape,A Tasteful and Elegant Home,"An elegant and comfortable home, thoughtfully ...",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,542901530,...,5.0,5.0,5.0,2026-004720STR,NaN,2,1,1,0,1.0
7329,1706229135493499688,https://www.airbnb.com/rooms/1706229135493499688,20260614073227,2026-06-14,city scrape,Luxury Modern Comfort Home,"Enjoy your own private lower-Level flat, thoug...",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,542901530,...,<NA>,<NA>,<NA>,2026-004720STR,NaN,2,1,1,0,<NA>
7330,1706477443981487094,https://www.airbnb.com/rooms/1706477443981487094,20260614073227,2026-06-14,city scrape,1BR Luxury Downtown | Bay Area,"A San Francisco landmark for over 70 years, th...",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,179605934,...,<NA>,<NA>,<NA>,Exempt,NaN,2,1,1,0,<NA>
7331,1706557052030067320,https://www.airbnb.com/rooms/1706557052030067320,20260614073227,2026-06-14,city scrape,Opera District Hotel | San Francisco,Soak up San Francisco’s dynamic arts culture a...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,179605934,...,<NA>,<NA>,<NA>,Exempt,NaN,2,1,1,0,<NA>

In [10]:
#del df['listing_url']

In [11]:
df[['last_scraped',
    'price_quote_checkin_date',
    'price_quote_checkout_date',
    'calendar_last_scraped',
    'first_review',
    'last_review']]

,last_scraped,price_quote_checkin_date,price_quote_checkout_date,calendar_last_scraped,first_review,last_review
0,2026-06-14,2026-06-26,2026-06-28,2026-06-14,2009-07-23,2026-05-26
1,2026-06-14,2026-07-31,2026-08-30,2026-06-14,2009-05-03,2017-08-06
2,2026-06-14,2026-06-23,2026-06-29,2026-06-14,2012-08-03,2026-06-02
3,2026-06-14,2026-07-30,2026-08-31,2026-06-14,2014-09-08,2026-04-03
4,2026-06-22,2026-06-24,2026-07-24,2026-06-22,2010-04-14,2019-06-28
...,...,...,...,...,...,...
7327,2026-06-14,2026-06-14,2026-06-16,2026-06-14,NaN,NaN
7328,2026-06-14,2026-06-14,2026-06-15,2026-06-14,2026-06-13,2026-06-13
7329,2026-06-14,2026-06-14,2026-06-15,2026-06-14,NaN,NaN
7330,2026-06-14,2026-06-18,2026-06-20,2026-06-14,NaN,NaN
7331,2026-06-14,2026-06-27,2026-06-29,2026-06-14,NaN,NaN

In [12]:
df[['last_scraped',
    'price_quote_checkin_date',
    'price_quote_checkout_date',
    'calendar_last_scraped',
    'first_review',
    'last_review']].info()

<class 'pandas.DataFrame'>
RangeIndex: 7332 entries, 0 to 7331
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   last_scraped               7332 non-null   str
 1   price_quote_checkin_date   6196 non-null   str
 2   price_quote_checkout_date  6196 non-null   str
 3   calendar_last_scraped      7332 non-null   str
 4   first_review               5748 non-null   str
 5   last_review                5748 non-null   str
dtypes: str(6)
memory usage: 343.8 KB

**Convert** data to proper type

In [13]:
date_cols = [
    'last_scraped',
    'price_quote_checkin_date',
    'price_quote_checkout_date',
    'calendar_last_scraped',
    'first_review',
    'last_review'
]

for col in date_cols:
    df[col] = pd.to_datetime(
        df[col],
        format='%Y-%m-%d',
        errors='coerce'
    )

df[date_cols].info()

<class 'pandas.DataFrame'>
RangeIndex: 7332 entries, 0 to 7331
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   last_scraped               7332 non-null   datetime64[us]
 1   price_quote_checkin_date   6196 non-null   datetime64[us]
 2   price_quote_checkout_date  6196 non-null   datetime64[us]
 3   calendar_last_scraped      7332 non-null   datetime64[us]
 4   first_review               5748 non-null   datetime64[us]
 5   last_review                5748 non-null   datetime64[us]
dtypes: datetime64[us](6)
memory usage: 343.8 KB

In [14]:
df[['last_scraped',
    'price_quote_checkin_date',
    'price_quote_checkout_date',
    'calendar_last_scraped',
    'first_review',
    'last_review']]

,last_scraped,price_quote_checkin_date,price_quote_checkout_date,calendar_last_scraped,first_review,last_review
0,2026-06-14,2026-06-26,2026-06-28,2026-06-14,2009-07-23,2026-05-26
1,2026-06-14,2026-07-31,2026-08-30,2026-06-14,2009-05-03,2017-08-06
2,2026-06-14,2026-06-23,2026-06-29,2026-06-14,2012-08-03,2026-06-02
3,2026-06-14,2026-07-30,2026-08-31,2026-06-14,2014-09-08,2026-04-03
4,2026-06-22,2026-06-24,2026-07-24,2026-06-22,2010-04-14,2019-06-28
...,...,...,...,...,...,...
7327,2026-06-14,2026-06-14,2026-06-16,2026-06-14,NaT,NaT
7328,2026-06-14,2026-06-14,2026-06-15,2026-06-14,2026-06-13,2026-06-13
7329,2026-06-14,2026-06-14,2026-06-15,2026-06-14,NaT,NaT
7330,2026-06-14,2026-06-18,2026-06-20,2026-06-14,NaT,NaT
7331,2026-06-14,2026-06-27,2026-06-29,2026-06-14,NaT,NaT

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7332 entries, 0 to 7331
Data columns (total 90 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            7332 non-null   Int64
 1   listing_url                                   7332 non-null   str
 2   scrape_id                                     7332 non-null   Int64
 3   last_scraped                                  7332 non-null   datetime64[us]
 4   source                                        7332 non-null   str
 5   name                                          7332 non-null   str
 6   description                                   7172 non-null   str
 7   neighborhood_overview                         0 non-null      float64
 8   picture_url                                   7332 non-null   str
 9   host_id                                       7332 non-null   Int64
 10  host_url                                      7332 non-null   str
 11  host_profile_id                               7242 non-null   Int64
 12  host_profile_url                              7239 non-null   str
 13  host_name                                     7242 non-null   str
 14  host_since                                    0 non-null      float64
 15  hosts_time_as_user_years                      7242 non-null   Int64
 16  hosts_time_as_user_months                     7242 non-null   Int64
 17  hosts_time_as_host_years                      7242 non-null   Int64
 18  hosts_time_as_host_months                     7242 non-null   Int64
 19  host_location                                 5670 non-null   str
 20  host_about                                    4452 non-null   str
 21  host_response_time                            0 non-null      float64
 22  host_response_rate                            0 non-null      float64
 23  host_acceptance_rate                          0 non-null      float64
 24  host_is_superhost                             7242 non-null   str
 25  host_thumbnail_url                            0 non-null      float64
 26  host_picture_url                              7242 non-null   str
 27  host_neighbourhood                            0 non-null      float64
 28  host_listings_count                           7242 non-null   Int64
 29  host_total_listings_count                     0 non-null      float64
 30  host_verifications                            0 non-null      float64
 31  host_has_profile_pic                          7242 non-null   str
 32  host_identity_verified                        7242 non-null   str
 33  neighbourhood                                 0 non-null      float64
 34  neighbourhood_cleansed                        7332 non-null   str
 35  neighbourhood_group_cleansed                  0 non-null      float64
 36  latitude                                      7332 non-null   Float64
 37  longitude                                     7332 non-null   Float64
 38  property_type                                 7332 non-null   str
 39  room_type                                     7332 non-null   str
 40  accommodates                                  7332 non-null   Int64
 41  bathrooms                                     5406 non-null   Float64
 42  bathrooms_text                                7252 non-null   str
 43  bedrooms                                      5341 non-null   Int64
 44  beds                                          5635 non-null   Int64
 45  amenities                                     7332 non-null   str
 46  price                                         5932 non-null   Float64
 47  price_quote_checkin_date                      6196 non-null   datetime64[us]
 48  price_quote_checkout_date                     6196 non-null   datetime64[us]
 49  price_quote_total_price                       5932 non-null   Float64
 50  price_quote_price_per_night                   5932 non-null   Float64
 51  price_quote_raw                               6196 non-null   str
 52  minimum_nights                                7328 non-null   Int64
 53  maximum_nights                                7328 non-null   Int64
 54  minimum_minimum_nights                        7328 non-null   Int64
 55  maximum_minimum_nights                        7328 non-null   Int64
 56  minimum_maximum_nights                        7328 non-null   Int64
 57  maximum_maximum_nights                        7328 non-null   Int64
 58  minimum_nights_avg_ntm                        7332 non-null   Float64
 59  maximum_nights_avg_ntm                        7332 non-null   Float64
 60  calendar_updated                              0 non-null      float64
 61  has_availability                              7281 non-null   str
 62  availability_30                               7332 non-null   Int64
 63  availability_60                               7332 non-null   Int64
 64  availability_90                               7332 non-null   Int64
 65  availability_365                              7332 non-null   Int64
 66  calendar_last_scraped                         7332 non-null   datetime64[us]
 67  number_of_reviews                             7332 non-null   Int64
 68  number_of_reviews_ltm                         7332 non-null   Int64
 69  number_of_reviews_l30d                        7332 non-null   Int64
 70  availability_eoy                              7332 non-null   Int64
 71  number_of_reviews_ly                          7332 non-null   Int64
 72  estimated_occupancy_l365d                     7332 non-null   Int64
 73  estimated_revenue_l365d                       5932 non-null   Int64
 74  first_review                                  5748 non-null   datetime64[us]
 75  last_review                                   5748 non-null   datetime64[us]
 76  review_scores_rating                          5748 non-null   Float64
 77  review_scores_accuracy                        5747 non-null   Float64
 78  review_scores_cleanliness                     5747 non-null   Float64
 79  review_scores_checkin                         5746 non-null   Float64
 80  review_scores_communication                   5747 non-null   Float64
 81  review_scores_location                        5746 non-null   Float64
 82  review_scores_value                           5746 non-null   Float64
 83  license                                       4860 non-null   str
 84  instant_bookable                              0 non-null      float64
 85  calculated_host_listings_count                7332 non-null   Int64
 86  calculated_host_listings_count_entire_homes   7332 non-null   Int64
 87  calculated_host_listings_count_private_rooms  7332 non-null   Int64
 88  calculated_host_listings_count_shared_rooms   7332 non-null   Int64
 89  reviews_per_month                             5748 non-null   Float64
dtypes: Float64(16), Int64(33), datetime64[us](6), float64(13), str(22)
memory usage: 5.4 MB

## Step 4 — Check missing values

**Ask:** Which columns have missing values, and what percentage is missing?

In [16]:
missing_values = pd.DataFrame({
    "Missing Count": df.isna().sum(),
    "Missing Percentage": (df.isna().mean() * 100).round(2)
})

missing_values = missing_values[
    missing_values["Missing Count"] > 0
].sort_values("Missing Percentage", ascending=False)

missing_values
print('13 col are empyty')

13 col are empyty

In [17]:
fully_empty_cols = df.columns[df.isna().all()]
fully_empty_cols

df.drop(columns=fully_empty_cols, inplace=True)

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7332 entries, 0 to 7331
Data columns (total 77 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            7332 non-null   Int64
 1   listing_url                                   7332 non-null   str
 2   scrape_id                                     7332 non-null   Int64
 3   last_scraped                                  7332 non-null   datetime64[us]
 4   source                                        7332 non-null   str
 5   name                                          7332 non-null   str
 6   description                                   7172 non-null   str
 7   picture_url                                   7332 non-null   str
 8   host_id                                       7332 non-null   Int64
 9   host_url                                      7332 non-null   str
 10  host_profile_id                               7242 non-null   Int64
 11  host_profile_url                              7239 non-null   str
 12  host_name                                     7242 non-null   str
 13  hosts_time_as_user_years                      7242 non-null   Int64
 14  hosts_time_as_user_months                     7242 non-null   Int64
 15  hosts_time_as_host_years                      7242 non-null   Int64
 16  hosts_time_as_host_months                     7242 non-null   Int64
 17  host_location                                 5670 non-null   str
 18  host_about                                    4452 non-null   str
 19  host_is_superhost                             7242 non-null   str
 20  host_picture_url                              7242 non-null   str
 21  host_listings_count                           7242 non-null   Int64
 22  host_has_profile_pic                          7242 non-null   str
 23  host_identity_verified                        7242 non-null   str
 24  neighbourhood_cleansed                        7332 non-null   str
 25  latitude                                      7332 non-null   Float64
 26  longitude                                     7332 non-null   Float64
 27  property_type                                 7332 non-null   str
 28  room_type                                     7332 non-null   str
 29  accommodates                                  7332 non-null   Int64
 30  bathrooms                                     5406 non-null   Float64
 31  bathrooms_text                                7252 non-null   str
 32  bedrooms                                      5341 non-null   Int64
 33  beds                                          5635 non-null   Int64
 34  amenities                                     7332 non-null   str
 35  price                                         5932 non-null   Float64
 36  price_quote_checkin_date                      6196 non-null   datetime64[us]
 37  price_quote_checkout_date                     6196 non-null   datetime64[us]
 38  price_quote_total_price                       5932 non-null   Float64
 39  price_quote_price_per_night                   5932 non-null   Float64
 40  price_quote_raw                               6196 non-null   str
 41  minimum_nights                                7328 non-null   Int64
 42  maximum_nights                                7328 non-null   Int64
 43  minimum_minimum_nights                        7328 non-null   Int64
 44  maximum_minimum_nights                        7328 non-null   Int64
 45  minimum_maximum_nights                        7328 non-null   Int64
 46  maximum_maximum_nights                        7328 non-null   Int64
 47  minimum_nights_avg_ntm                        7332 non-null   Float64
 48  maximum_nights_avg_ntm                        7332 non-null   Float64
 49  has_availability                              7281 non-null   str
 50  availability_30                               7332 non-null   Int64
 51  availability_60                               7332 non-null   Int64
 52  availability_90                               7332 non-null   Int64
 53  availability_365                              7332 non-null   Int64
 54  calendar_last_scraped                         7332 non-null   datetime64[us]
 55  number_of_reviews                             7332 non-null   Int64
 56  number_of_reviews_ltm                         7332 non-null   Int64
 57  number_of_reviews_l30d                        7332 non-null   Int64
 58  availability_eoy                              7332 non-null   Int64
 59  number_of_reviews_ly                          7332 non-null   Int64
 60  estimated_occupancy_l365d                     7332 non-null   Int64
 61  estimated_revenue_l365d                       5932 non-null   Int64
 62  first_review                                  5748 non-null   datetime64[us]
 63  last_review                                   5748 non-null   datetime64[us]
 64  review_scores_rating                          5748 non-null   Float64
 65  review_scores_accuracy                        5747 non-null   Float64
 66  review_scores_cleanliness                     5747 non-null   Float64
 67  review_scores_checkin                         5746 non-null   Float64
 68  review_scores_communication                   5747 non-null   Float64
 69  review_scores_location                        5746 non-null   Float64
 70  review_scores_value                           5746 non-null   Float64
 71  license                                       4860 non-null   str
 72  calculated_host_listings_count                7332 non-null   Int64
 73  calculated_host_listings_count_entire_homes   7332 non-null   Int64
 74  calculated_host_listings_count_private_rooms  7332 non-null   Int64
 75  calculated_host_listings_count_shared_rooms   7332 non-null   Int64
 76  reviews_per_month                             5748 non-null   Float64
dtypes: Float64(16), Int64(33), datetime64[us](6), str(22)
memory usage: 4.7 MB

## Step 5 — Check duplicates and uniqueness

**Ask:** Are there duplicated rows?

In [19]:
for column in df.columns:
    print(df[column].duplicated().value_counts(()))
    print('___________________')

id
False    7332
Name: count, dtype: int64
___________________
listing_url
False    7332
Name: count, dtype: int64
___________________
scrape_id
True     7331
False       1
Name: count, dtype: int64
___________________
last_scraped
True     7330
False       2
Name: count, dtype: int64
___________________
source
True     7330
False       2
Name: count, dtype: int64
___________________
name
False    6829
True      503
Name: count, dtype: int64
___________________
description
False    5789
True     1543
Name: count, dtype: int64
___________________
picture_url
False    6971
True      361
Name: count, dtype: int64
___________________
host_id
True     3833
False    3499
Name: count, dtype: int64
___________________
host_url
True     3833
False    3499
Name: count, dtype: int64
___________________
host_profile_id
True     3857
False    3475
Name: count, dtype: int64
___________________
host_profile_url
True     3857
False    3475
Name: count, dtype: int64
___________________
host_name
True     5384
False    1948
Name: count, dtype: int64
___________________
hosts_time_as_user_years
True     7313
False      19
Name: count, dtype: int64
___________________
hosts_time_as_user_months
True     7319
False      13
Name: count, dtype: int64
___________________
hosts_time_as_host_years
True     7315
False      17
Name: count, dtype: int64
___________________
hosts_time_as_host_months
True     7319
False      13
Name: count, dtype: int64
___________________
host_location
True     7114
False     218
Name: count, dtype: int64
___________________
host_about
True     5150
False    2182
Name: count, dtype: int64
___________________
host_is_superhost
True     7329
False       3
Name: count, dtype: int64
___________________
host_picture_url
True     3874
False    3458
Name: count, dtype: int64
___________________
host_listings_count
True     7206
False     126
Name: count, dtype: int64
___________________
host_has_profile_pic
True     7329
False       3
Name: count, dtype: int64
___________________
host_identity_verified
True     7329
False       3
Name: count, dtype: int64
___________________
neighbourhood_cleansed
True     7296
False      36
Name: count, dtype: int64
___________________
latitude
False    5191
True     2141
Name: count, dtype: int64
___________________
longitude
False    5281
True     2051
Name: count, dtype: int64
___________________
property_type
True     7283
False      49
Name: count, dtype: int64
___________________
room_type
True     7328
False       4
Name: count, dtype: int64
___________________
accommodates
True     7316
False      16
Name: count, dtype: int64
___________________
bathrooms
True     7315
False      17
Name: count, dtype: int64
___________________
bathrooms_text
True     7298
False      34
Name: count, dtype: int64
___________________
bedrooms
True     7318
False      14
Name: count, dtype: int64
___________________
beds
True     7316
False      16
Name: count, dtype: int64
___________________
amenities
False    6187
True     1145
Name: count, dtype: int64
___________________
price
True     3682
False    3650
Name: count, dtype: int64
___________________
price_quote_checkin_date
True     7043
False     289
Name: count, dtype: int64
___________________
price_quote_checkout_date
True     7018
False     314
Name: count, dtype: int64
___________________
price_quote_total_price
True     3775
False    3557
Name: count, dtype: int64
___________________
price_quote_price_per_night
True     3682
False    3650
Name: count, dtype: int64
___________________
price_quote_raw
False    5534
True     1798
Name: count, dtype: int64
___________________
minimum_nights
True     7280
False      52
Name: count, dtype: int64
___________________
maximum_nights
True     7195
False     137
Name: count, dtype: int64
___________________
minimum_minimum_nights
True     7280
False      52
Name: count, dtype: int64
___________________
maximum_minimum_nights
True     7258
False      74
Name: count, dtype: int64
___________________
minimum_maximum_nights
True     7194
False     138
Name: count, dtype: int64
___________________
maximum_maximum_nights
True     7195
False     137
Name: count, dtype: int64
___________________
minimum_nights_avg_ntm
True     7151
False     181
Name: count, dtype: int64
___________________
maximum_nights_avg_ntm
True     6868
False     464
Name: count, dtype: int64
___________________
has_availability
True     7329
False       3
Name: count, dtype: int64
___________________
availability_30
True     7301
False      31
Name: count, dtype: int64
___________________
availability_60
True     7271
False      61
Name: count, dtype: int64
___________________
availability_90
True     7241
False      91
Name: count, dtype: int64
___________________
availability_365
True     6966
False     366
Name: count, dtype: int64
___________________
calendar_last_scraped
True     7330
False       2
Name: count, dtype: int64
___________________
number_of_reviews
True     6801
False     531
Name: count, dtype: int64
___________________
number_of_reviews_ltm
True     7202
False     130
Name: count, dtype: int64
___________________
number_of_reviews_l30d
True     7307
False      25
Name: count, dtype: int64
___________________
availability_eoy
True     7130
False     202
Name: count, dtype: int64
___________________
number_of_reviews_ly
True     7207
False     125
Name: count, dtype: int64
___________________
estimated_occupancy_l365d
True     7278
False      54
Name: count, dtype: int64
___________________
estimated_revenue_l365d
True     3908
False    3424
Name: count, dtype: int64
___________________
first_review
True     4335
False    2997
Name: count, dtype: int64
___________________
last_review
True     6174
False    1158
Name: count, dtype: int64
___________________
review_scores_rating
True     7213
False     119
Name: count, dtype: int64
___________________
review_scores_accuracy
True     7223
False     109
Name: count, dtype: int64
___________________
review_scores_cleanliness
True     7201
False     131
Name: count, dtype: int64
___________________
review_scores_checkin
True     7241
False      91
Name: count, dtype: int64
___________________
review_scores_communication
True     7237
False      95
Name: count, dtype: int64
___________________
review_scores_location
True     7189
False     143
Name: count, dtype: int64
___________________
review_scores_value
True     7207
False     125
Name: count, dtype: int64
___________________
license
True     5149
False    2183
Name: count, dtype: int64
___________________
calculated_host_listings_count
True     7288
False      44
Name: count, dtype: int64
___________________
calculated_host_listings_count_entire_homes
True     7299
False      33
Name: count, dtype: int64
___________________
calculated_host_listings_count_private_rooms
True     7305
False      27
Name: count, dtype: int64
___________________
calculated_host_listings_count_shared_rooms
True     7325
False       7
Name: count, dtype: int64
___________________
reviews_per_month
True     6684
False     648
Name: count, dtype: int64
___________________

In [20]:
duplicated = df.duplicated(keep=False).sum()
print(duplicated)

0

In [21]:
unique_rows = df.drop_duplicates()
print(unique_rows)

                       id                                       listing_url  \
0                     958                  https://www.airbnb.com/rooms/958
1                    5858                 https://www.airbnb.com/rooms/5858
2                    8014                 https://www.airbnb.com/rooms/8014
3                    8142                 https://www.airbnb.com/rooms/8142
4                    8339                 https://www.airbnb.com/rooms/8339
...                   ...                                               ...
7327  1706112761356045678  https://www.airbnb.com/rooms/1706112761356045678
7328  1706228944697932884  https://www.airbnb.com/rooms/1706228944697932884
7329  1706229135493499688  https://www.airbnb.com/rooms/1706229135493499688
7330  1706477443981487094  https://www.airbnb.com/rooms/1706477443981487094
7331  1706557052030067320  https://www.airbnb.com/rooms/1706557052030067320

           scrape_id last_scraped           source  \
0     20260614073227   2026-06-14      city scrape
1     20260614073227   2026-06-14      city scrape
2     20260614073227   2026-06-14      city scrape
3     20260614073227   2026-06-14      city scrape
4     20260614073227   2026-06-22  previous scrape
...              ...          ...              ...
7327  20260614073227   2026-06-14      city scrape
7328  20260614073227   2026-06-14      city scrape
7329  20260614073227   2026-06-14      city scrape
7330  20260614073227   2026-06-14      city scrape
7331  20260614073227   2026-06-14      city scrape

                                                   name  \
0                 Bright, Modern Garden Unit - 1BR/1BTH
1                                    Creative Sanctuary
2        female HOST quiet fast internet market parking
3     *FriendlyRoom Apt. Style -UCSF/USF - San Franc...
4                       Historic Alamo Square Victorian
...                                                 ...
7327                                    1 Bedroom in SF
7328                        A Tasteful and Elegant Home
7329                         Luxury Modern Comfort Home
7330                     1BR Luxury Downtown | Bay Area
7331               Opera District Hotel | San Francisco

                                            description  \
0     **Please note that the house behind our backya...
1     We live in a large Victorian house on a quiet ...
2     Room is on the second floor so it gets a good ...
3     Nice and good public transportation.  7 minute...
4     For creative humans who love art, space, photo...
...                                                 ...
7327  This stylish and unique place sets the stage f...
7328  An elegant and comfortable home, thoughtfully ...
7329  Enjoy your own private lower-Level flat, thoug...
7330  A San Francisco landmark for over 70 years, th...
7331  Soak up San Francisco’s dynamic arts culture a...

                                            picture_url    host_id  \
0     https://a0.muscache.com/pictures/be1bf5ac-a955...       1169
1     https://a0.muscache.com/pictures/hosting/Hosti...       8904
2     https://a0.muscache.com/pictures/2cc1fc3d-0ae0...      22402
3     https://a0.muscache.com/pictures/hosting/Hosti...      21994
4     https://a0.muscache.com/pictures/miso/Hosting-...      24215
...                                                 ...        ...
7327  https://a0.muscache.com/pictures/hosting/Hosti...   67057435
7328  https://a0.muscache.com/pictures/hosting/Hosti...  542901530
7329  https://a0.muscache.com/pictures/hosting/Hosti...  542901530
7330  https://a0.muscache.com/pictures/hosting/Hosti...  179605934
7331  https://a0.muscache.com/pictures/hosting/Hosti...  179605934

                                         host_url  ...  review_scores_checkin  \
0          https://www.airbnb.com/users/show/1169  ...                   4.96
1          https://www.airbnb.com/users/show/8904  ...                   4.89
2         https://www.airbnb.com/users/show/22402  ...                   4.92
3         https://www.airbnb.com/users/show/21994  ...                   4.82
4         https://www.airbnb.com/users/show/24215  ...                   4.94
...                                           ...  ...                    ...
7327   https://www.airbnb.com/users/show/67057435  ...                   <NA>
7328  https://www.airbnb.com/users/show/542901530  ...                    5.0
7329  https://www.airbnb.com/users/show/542901530  ...                   <NA>
7330  https://www.airbnb.com/users/show/179605934  ...                   <NA>
7331  https://www.airbnb.com/users/show/179605934  ...                   <NA>

     review_scores_communication review_scores_location  review_scores_value  \
0                            4.9                   4.97                 4.78
1                           4.85                   4.77                 4.68
2                           4.95                    4.6                 4.67
3                           4.82                   4.73                 4.73
4                            5.0                   4.94                 4.75
...                          ...                    ...                  ...
7327                        <NA>                   <NA>                 <NA>
7328                         5.0                    5.0                  5.0
7329                        <NA>                   <NA>                 <NA>
7330                        <NA>                   <NA>                 <NA>
7331                        <NA>                   <NA>                 <NA>

             license  calculated_host_listings_count  \
0        STR-0006854                               1
1                NaN                               1
2        STR-0000974                               2
3                NaN                              22
4        STR-0000264                               1
...              ...                             ...
7327          Exempt                               1
7328  2026-004720STR                               2
7329  2026-004720STR                               2
7330          Exempt                               2
7331          Exempt                               2

      calculated_host_listings_count_entire_homes  \
0                                               1
1                                               1
2                                               0
3                                               0
4                                               1
...                                           ...
7327                                            0
7328                                            1
7329                                            1
7330                                            1
7331                                            1

     calculated_host_listings_count_private_rooms  \
0                                               0
1                                               0
2                                               2
3                                              22
4                                               0
...                                           ...
7327                                            1
7328                                            1
7329                                            1
7330                                            1
7331                                            1

     calculated_host_listings_count_shared_rooms reviews_per_month
0                                              0              2.58
1                                              0               0.5
2                                              0              0.55
3                                              0              0.08
4                                              0              0.13
...                                          ...               ...
7327                                           0              <NA>
7328                                           0               1.0
7329                                           0              <NA>
7330                                           0              <NA>
7331                                           0              <NA>

[7332 rows x 77 columns]

In [22]:
unique = df[~df.duplicated(keep=False)]
unique.shape[0]

#no duplicated rows

7332

## Step 6 — Clean obvious data-quality issues

For practice, we will:

- remove exact duplicate rows;
- fill missing categorical values with `"Unknown"`;

In [23]:
df = df.drop_duplicates().reset_index(drop=True)

In [24]:
categorical_columns = df.select_dtypes(
    include=["object", "string"]
).columns

df[categorical_columns] = df[categorical_columns].fillna("Unknown")

## Step 7 — Descriptive statistics

**Ask:** What are the typical values, ranges, and variability?

In [25]:
df.describe(include="all")

,id,listing_url,scrape_id,last_scraped,source,name,description,picture_url,host_id,host_url,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,7332.0,7332,7332.0,7332,7332,7332,7332,7332,7332.0,7332,...,5746.0,5747.0,5746.0,5746.0,7332,7332.0,7332.0,7332.0,7332.0,5748.0
unique,<NA>,7332,<NA>,NaN,2,6829,5789,6971,<NA>,3499,...,<NA>,<NA>,<NA>,<NA>,2183,<NA>,<NA>,<NA>,<NA>,<NA>
top,<NA>,https://www.airbnb.com/rooms/958,<NA>,NaN,city scrape,Chic King Suite at Wyndham Donatello in SF,Unknown,https://a0.muscache.com/pictures/bbb4ace5-01ce...,<NA>,https://www.airbnb.com/users/show/107434423,...,<NA>,<NA>,<NA>,<NA>,Unknown,<NA>,<NA>,<NA>,<NA>,<NA>
freq,<NA>,1,<NA>,NaN,5712,30,160,23,<NA>,179,...,<NA>,<NA>,<NA>,<NA>,2472,<NA>,<NA>,<NA>,<NA>,<NA>
mean,647051552805467648.0,NaN,20260614073227.0,2026-06-15 18:25:20.130933,NaN,NaN,NaN,NaN,2748086439599955.0,NaN,...,4.890031,4.868937,4.801843,4.692835,NaN,15.101746,10.235952,3.86252,0.04419,1.231889
min,958.0,NaN,20260614073227.0,2026-06-14 00:00:00,NaN,NaN,NaN,NaN,1169.0,NaN,...,1.0,1.0,1.0,1.0,NaN,1.0,0.0,0.0,0.0,0.01
25%,31068401.5,NaN,20260614073227.0,2026-06-14 00:00:00,NaN,NaN,NaN,NaN,11395542.75,NaN,...,4.89,4.88,4.77,4.63,NaN,1.0,0.0,0.0,0.0,0.17
50%,688339976572930048.0,NaN,20260614073227.0,2026-06-14 00:00:00,NaN,NaN,NaN,NaN,91402886.0,NaN,...,4.97,4.97,4.91,4.79,NaN,3.0,1.0,0.0,0.0,0.46
75%,1256909402571933440.0,NaN,20260614073227.0,2026-06-14 00:00:00,NaN,NaN,NaN,NaN,395260079.5,NaN,...,5.0,5.0,5.0,4.91,NaN,13.0,3.0,3.0,0.0,1.6
max,1706557052030067200.0,NaN,20260614073227.0,2026-06-22 00:00:00,NaN,NaN,NaN,NaN,1701866412446098432.0,NaN,...,5.0,5.0,5.0,5.0,NaN,179.0,179.0,60.0,7.0,56.82
std,634415859833451904.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,67879461832537112.0,NaN,...,0.282934,0.335667,0.351332,0.401865,NaN,31.663565,31.164819,9.164641,0.484331,1.989447

In [26]:
summary = df.select_dtypes(include="number").describe().T

summary["median"] = df.select_dtypes(include="number").median()
summary["range"] = summary["max"] - summary["min"]

summary[["count", "mean", "median", "std", "min", "max", "range"]].round(3)

,count,mean,median,std,min,max,range
id,7332.0,647051552805467648.0,688339976572930048.0,634415859833451776.0,958.0,1706557052030067200.0,1706557052030066176.0
scrape_id,7332.0,20260614073227.0,20260614073227.0,0.0,20260614073227.0,20260614073227.0,0.0
host_id,7332.0,2748086439599955.0,91402886.0,67879461832537112.0,1169.0,1701866412446098432.0,1701866412446097152.0
host_profile_id,7242.0,1470258175529103104.0,1465579310518147072.0,25655204253603156.0,1462506189282101760.0,1706228945504794112.0,243722756222692352.0
hosts_time_as_user_years,7242.0,8.589,9.0,4.232,0.0,17.0,17.0
hosts_time_as_user_months,7242.0,5.472,5.0,3.477,0.0,11.0,11.0
hosts_time_as_host_years,7242.0,6.713,7.0,4.18,0.0,15.0,15.0
hosts_time_as_host_months,7242.0,5.417,5.0,3.341,0.0,11.0,11.0
host_listings_count,7242.0,291.966,4.0,945.154,1.0,5978.0,5977.0
latitude,7332.0,37.771,37.777,0.023,37.709,37.81,0.101
longitude,7332.0,-122.429,-122.421,0.027,-122.512,-122.368,0.143
accommodates,7332.0,3.419,2.0,2.249,1.0,16.0,15.0
bathrooms,5406.0,1.368,1.0,1.075,0.5,27.0,26.5
bedrooms,5341.0,1.697,1.0,1.054,0.0,23.0,23.0
beds,5635.0,1.93,2.0,1.367,1.0,26.0,25.0
price,5932.0,413.859,252.29,1431.985,4.14,99999.0,99994.86
price_quote_total_price,5932.0,3104.203,1344.96,6862.337,47.0,257555.66,257508.66
price_quote_price_per_night,5932.0,413.859,252.29,1431.985,4.14,99999.0,99994.86
minimum_nights,7328.0,18.512,3.0,46.492,1.0,1125.0,1124.0
maximum_nights,7328.0,7033890.573,365.0,122704336.962,1.0,2147483647.0,2147483646.0
minimum_minimum_nights,7328.0,18.512,3.0,46.492,1.0,1125.0,1124.0
maximum_minimum_nights,7328.0,25.929,4.0,66.484,1.0,1125.0,1124.0
minimum_maximum_nights,7328.0,5861630.614,365.0,112043892.524,1.0,2147483647.0,2147483646.0
maximum_maximum_nights,7328.0,7033890.573,365.0,122704336.962,1.0,2147483647.0,2147483646.0
minimum_nights_avg_ntm,7332.0,19.708,3.0,50.56,1.0,1125.0,1124.0
maximum_nights_avg_ntm,7332.0,6479542.71,365.0,115138394.217,1.0,2147483647.0,2147483646.0
availability_30,7332.0,7.711,2.0,9.818,0.0,30.0,30.0
availability_60,7332.0,18.596,10.0,20.636,0.0,60.0,60.0
availability_90,7332.0,34.218,29.0,30.251,0.0,90.0,90.0
availability_365,7332.0,181.628,196.0,126.57,0.0,365.0,365.0
number_of_reviews,7332.0,59.206,9.0,123.255,0.0,1500.0,1500.0
number_of_reviews_ltm,7332.0,9.385,1.0,19.67,0.0,365.0,365.0
number_of_reviews_l30d,7332.0,0.768,0.0,1.963,0.0,63.0,63.0
availability_eoy,7332.0,97.488,111.0,67.925,0.0,201.0,201.0
number_of_reviews_ly,7332.0,8.751,1.0,18.488,0.0,281.0,281.0
estimated_occupancy_l365d,7332.0,89.086,44.0,100.736,0.0,255.0,255.0
estimated_revenue_l365d,5932.0,31358.6,13535.5,46946.473,0.0,531076.0,531076.0
review_scores_rating,5748.0,4.803,4.92,0.368,1.0,5.0,4.0
review_scores_accuracy,5747.0,4.824,4.93,0.363,1.0,5.0,4.0
review_scores_cleanliness,5747.0,4.791,4.92,0.375,1.0,5.0,4.0
review_scores_checkin,5746.0,4.89,4.97,0.283,1.0,5.0,4.0
review_scores_communication,5747.0,4.869,4.97,0.336,1.0,5.0,4.0
review_scores_location,5746.0,4.802,4.91,0.351,1.0,5.0,4.0
review_scores_value,5746.0,4.693,4.79,0.402,1.0,5.0,4.0
calculated_host_listings_count,7332.0,15.102,3.0,31.664,1.0,179.0,178.0
calculated_host_listings_count_entire_homes,7332.0,10.236,1.0,31.165,0.0,179.0,179.0
calculated_host_listings_count_private_rooms,7332.0,3.863,0.0,9.165,0.0,60.0,60.0
calculated_host_listings_count_shared_rooms,7332.0,0.044,0.0,0.484,0.0,7.0,7.0
reviews_per_month,5748.0,1.232,0.46,1.989,0.01,56.82,56.81

## Step 8 — Explore categorical variables

**Ask:** What are the most common segments, regions, categories, and shipping modes?

In [27]:
# categorical_cols = df.select_dtypes(include='object')

In [ ]:
categorical_cols = [
    "source",
    "host_is_superhost",
    "host_has_profile_pic",
    "host_identity_verified",
    "neighbourhood_cleansed",
    "property_type",
    "room_type",
    "has_availability",
]

**Visualize** the categorical columns

In [46]:
numeric_df = df.select_dtypes(include="number")

print(numeric_df)

                       id       scrape_id    host_id      host_profile_id  \
0                     958  20260614073227       1169  1462506189282101760
1                    5858  20260614073227       8904  1462506623299518208
2                    8014  20260614073227      22402  1462506962679395840
3                    8142  20260614073227      21994  1462506956810615040
4                    8339  20260614073227      24215  1462506994551169536
...                   ...             ...        ...                  ...
7327  1706112761356045678  20260614073227   67057435  1699364323265379328
7328  1706228944697932884  20260614073227  542901530  1706228945504794112
7329  1706229135493499688  20260614073227  542901530  1706228945504794112
7330  1706477443981487094  20260614073227  179605934  1468734525069975040
7331  1706557052030067320  20260614073227  179605934  1468734525069975040

      hosts_time_as_user_years  hosts_time_as_user_months  \
0                           17                         10
1                           17                          3
2                           16                         11
3                           16                         11
4                           16                         11
...                        ...                        ...
7327                        10                          2
7328                         2                          7
7329                         2                          7
7330                         8                          2
7331                         8                          2

      hosts_time_as_host_years  hosts_time_as_host_months  \
0                           15                          5
1                           15                          5
2                           13                         10
3                           15                          5
4                           15                          5
...                        ...                        ...
7327                         0                          0
7328                         0                          0
7329                         0                          0
7330                         1                          4
7331                         1                          4

      host_listings_count   latitude  ...  review_scores_cleanliness  \
0                       1   37.77028  ...                       4.93
1                       2   37.74474  ...                       4.87
2                       2   37.73077  ...                       4.33
3                      22   37.76555  ...                       4.55
4                       1   37.77377  ...                        5.0
...                   ...        ...  ...                        ...
7327                    3  37.778401  ...                       <NA>
7328                    2   37.73539  ...                        5.0
7329                    2  37.733192  ...                       <NA>
7330                  121   37.78899  ...                       <NA>
7331                  121   37.77876  ...                       <NA>

      review_scores_checkin  review_scores_communication  \
0                      4.96                          4.9
1                      4.89                         4.85
2                      4.92                         4.95
3                      4.82                         4.82
4                      4.94                          5.0
...                     ...                          ...
7327                   <NA>                         <NA>
7328                    5.0                          5.0
7329                   <NA>                         <NA>
7330                   <NA>                         <NA>
7331                   <NA>                         <NA>

      review_scores_location  review_scores_value  \
0                       4.97                 4.78
1                       4.77                 4.68
2                        4.6                 4.67
3                       4.73                 4.73
4                       4.94                 4.75
...                      ...                  ...
7327                    <NA>                 <NA>
7328                     5.0                  5.0
7329                    <NA>                 <NA>
7330                    <NA>                 <NA>
7331                    <NA>                 <NA>

      calculated_host_listings_count  \
0                                  1
1                                  1
2                                  2
3                                 22
4                                  1
...                              ...
7327                               1
7328                               2
7329                               2
7330                               2
7331                               2

      calculated_host_listings_count_entire_homes  \
0                                               1
1                                               1
2                                               0
3                                               0
4                                               1
...                                           ...
7327                                            0
7328                                            1
7329                                            1
7330                                            1
7331                                            1

      calculated_host_listings_count_private_rooms  \
0                                                0
1                                                0
2                                                2
3                                               22
4                                                0
...                                            ...
7327                                             1
7328                                             1
7329                                             1
7330                                             1
7331                                             1

      calculated_host_listings_count_shared_rooms  reviews_per_month
0                                               0               2.58
1                                               0                0.5
2                                               0               0.55
3                                               0               0.08
4                                               0               0.13
...                                           ...                ...
7327                                            0               <NA>
7328                                            0                1.0
7329                                            0               <NA>
7330                                            0               <NA>
7331                                            0               <NA>

[7332 rows x 49 columns]

In [47]:

for col in categorical_cols:

    value_counts = (
        df[col]
        .value_counts()
        .head(12)
        .reset_index()
    )

    value_counts.columns = [col, "Count"]

    fig = px.bar(
        value_counts,
        x=col,
        y="Count",
        text_auto=True,
        title=f"{col.title()} - Frequency Distribution"
    )

    fig.show()

## Step 9 — Explore numerical distributions

Histograms help identify skewness, concentration, and unusual values.

In [48]:
numbers=df.select_dtypes(include=['number'])

In [52]:
hist_cols = [
    "accommodates",
    "bathrooms",
    "bedrooms",
    "beds",
    "price",
    "price_quote_price_per_night",
    "minimum_nights",
    "availability_365",
    "number_of_reviews",
    "estimated_occupancy_l365d",
    "estimated_revenue_l365d",
    "review_scores_rating",
    "reviews_per_month"
]

**Visualize** the numerical columns

In [53]:
df

,id,listing_url,scrape_id,last_scraped,source,name,description,picture_url,host_id,host_url,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,958,https://www.airbnb.com/rooms/958,20260614073227,2026-06-14,city scrape,"Bright, Modern Garden Unit - 1BR/1BTH",**Please note that the house behind our backya...,https://a0.muscache.com/pictures/be1bf5ac-a955...,1169,https://www.airbnb.com/users/show/1169,...,4.96,4.9,4.97,4.78,STR-0006854,1,1,0,0,2.58
1,5858,https://www.airbnb.com/rooms/5858,20260614073227,2026-06-14,city scrape,Creative Sanctuary,We live in a large Victorian house on a quiet ...,https://a0.muscache.com/pictures/hosting/Hosti...,8904,https://www.airbnb.com/users/show/8904,...,4.89,4.85,4.77,4.68,Unknown,1,1,0,0,0.5
2,8014,https://www.airbnb.com/rooms/8014,20260614073227,2026-06-14,city scrape,female HOST quiet fast internet market parking,Room is on the second floor so it gets a good ...,https://a0.muscache.com/pictures/2cc1fc3d-0ae0...,22402,https://www.airbnb.com/users/show/22402,...,4.92,4.95,4.6,4.67,STR-0000974,2,0,2,0,0.55
3,8142,https://www.airbnb.com/rooms/8142,20260614073227,2026-06-14,city scrape,*FriendlyRoom Apt. Style -UCSF/USF - San Franc...,Nice and good public transportation. 7 minute...,https://a0.muscache.com/pictures/hosting/Hosti...,21994,https://www.airbnb.com/users/show/21994,...,4.82,4.82,4.73,4.73,Unknown,22,0,22,0,0.08
4,8339,https://www.airbnb.com/rooms/8339,20260614073227,2026-06-22,previous scrape,Historic Alamo Square Victorian,"For creative humans who love art, space, photo...",https://a0.muscache.com/pictures/miso/Hosting-...,24215,https://www.airbnb.com/users/show/24215,...,4.94,5.0,4.94,4.75,STR-0000264,1,1,0,0,0.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7327,1706112761356045678,https://www.airbnb.com/rooms/1706112761356045678,20260614073227,2026-06-14,city scrape,1 Bedroom in SF,This stylish and unique place sets the stage f...,https://a0.muscache.com/pictures/hosting/Hosti...,67057435,https://www.airbnb.com/users/show/67057435,...,<NA>,<NA>,<NA>,<NA>,Exempt,1,0,1,0,<NA>
7328,1706228944697932884,https://www.airbnb.com/rooms/1706228944697932884,20260614073227,2026-06-14,city scrape,A Tasteful and Elegant Home,"An elegant and comfortable home, thoughtfully ...",https://a0.muscache.com/pictures/hosting/Hosti...,542901530,https://www.airbnb.com/users/show/542901530,...,5.0,5.0,5.0,5.0,2026-004720STR,2,1,1,0,1.0
7329,1706229135493499688,https://www.airbnb.com/rooms/1706229135493499688,20260614073227,2026-06-14,city scrape,Luxury Modern Comfort Home,"Enjoy your own private lower-Level flat, thoug...",https://a0.muscache.com/pictures/hosting/Hosti...,542901530,https://www.airbnb.com/users/show/542901530,...,<NA>,<NA>,<NA>,<NA>,2026-004720STR,2,1,1,0,<NA>
7330,1706477443981487094,https://www.airbnb.com/rooms/1706477443981487094,20260614073227,2026-06-14,city scrape,1BR Luxury Downtown | Bay Area,"A San Francisco landmark for over 70 years, th...",https://a0.muscache.com/pictures/hosting/Hosti...,179605934,https://www.airbnb.com/users/show/179605934,...,<NA>,<NA>,<NA>,<NA>,Exempt,2,1,1,0,<NA>
7331,1706557052030067320,https://www.airbnb.com/rooms/1706557052030067320,20260614073227,2026-06-14,city scrape,Opera District Hotel | San Francisco,Soak up San Francisco’s dynamic arts culture a...,https://a0.muscache.com/pictures/hosting/Hosti...,179605934,https://www.airbnb.com/users/show/179605934,...,<NA>,<NA>,<NA>,<NA>,Exempt,2,1,1,0,<NA>

In [135]:


for col in hist_cols:

    fig = px.histogram(df,x=col,
        nbins=30,
        title=f"Distribution of {col.title()}",
        labels={
            col: col.title(),
            "count": "Frequency"
        })

    fig.show()

## Step 10 — Detect outliers using IQR

The common IQR rule defines potential outliers as values below:

`Q1 - 1.5 × IQR`

or above:

`Q3 + 1.5 × IQR`

In [137]:
outlier_summary = []
outliers = {}

for col in numbers.columns:
    values = numbers[col].dropna()

    q1 = values.quantile(0.25)
    q3 = values.quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    mask = (numbers[col] < lower_bound) | (numbers[col] > upper_bound)

    outliers[col] = df.loc[mask]

    outlier_summary.append({
        "Column": col,
        "Q1": q1,
        "Q3": q3,
        "IQR": iqr,
        "Lower Bound": lower_bound,
        "Upper Bound": upper_bound,
        "Outlier Count": mask.sum()
    })

outlier_summary = pd.DataFrame(outlier_summary)

outlier_summary.sort_values(
    by="Outlier Count",
    ascending=False
)

,Column,Q1,Q3,IQR,Lower Bound,Upper Bound,Outlier Count
8,host_listings_count,1.000000e+00,3.000000e+01,2.900000e+01,-4.250000e+01,7.350000e+01,1383
34,number_of_reviews_ly,0.000000e+00,7.000000e+00,7.000000e+00,-1.050000e+01,1.750000e+01,1180
45,calculated_host_listings_count_entire_homes,0.000000e+00,3.000000e+00,3.000000e+00,-4.500000e+00,7.500000e+00,1169
31,number_of_reviews_ltm,0.000000e+00,8.000000e+00,8.000000e+00,-1.200000e+01,2.000000e+01,1137
46,calculated_host_listings_count_private_rooms,0.000000e+00,3.000000e+00,3.000000e+00,-4.500000e+00,7.500000e+00,1011
30,number_of_reviews,1.000000e+00,5.500000e+01,5.400000e+01,-8.000000e+01,1.360000e+02,997
44,calculated_host_listings_count,1.000000e+00,1.300000e+01,1.200000e+01,-1.700000e+01,3.100000e+01,980
32,number_of_reviews_l30d,0.000000e+00,1.000000e+00,1.000000e+00,-1.500000e+00,2.500000e+00,782
41,review_scores_communication,4.880000e+00,5.000000e+00,1.200000e-01,4.700000e+00,5.180000e+00,616
14,beds,1.000000e+00,2.000000e+00,1.000000e+00,-5.000000e-01,3.500000e+00,586
38,review_scores_accuracy,4.810000e+00,5.000000e+00,1.900000e-01,4.525000e+00,5.285000e+00,545
40,review_scores_checkin,4.890000e+00,5.000000e+00,1.100000e-01,4.725000e+00,5.165000e+00,527
15,price,1.520000e+02,4.385625e+02,2.865625e+02,-2.778438e+02,8.684062e+02,521
17,price_quote_price_per_night,1.520000e+02,4.385625e+02,2.865625e+02,-2.778438e+02,8.684062e+02,521
48,reviews_per_month,1.700000e-01,1.600000e+00,1.430000e+00,-1.975000e+00,3.745000e+00,493
37,review_scores_rating,4.770000e+00,5.000000e+00,2.300000e-01,4.425000e+00,5.345000e+00,454
43,review_scores_value,4.630000e+00,4.910000e+00,2.800000e-01,4.210000e+00,5.330000e+00,452
39,review_scores_cleanliness,4.750000e+00,5.000000e+00,2.500000e-01,4.375000e+00,5.375000e+00,451
42,review_scores_location,4.770000e+00,5.000000e+00,2.300000e-01,4.425000e+00,5.345000e+00,451
11,accommodates,2.000000e+00,4.000000e+00,2.000000e+00,-1.000000e+00,7.000000e+00,426
16,price_quote_total_price,4.839650e+02,3.891970e+03,3.408005e+03,-4.628042e+03,9.003977e+03,384
12,bathrooms,1.000000e+00,1.500000e+00,5.000000e-01,2.500000e-01,2.250000e+00,383
10,longitude,-1.224418e+02,-1.224102e+02,3.157750e-02,-1.224892e+02,-1.223629e+02,365
36,estimated_revenue_l365d,0.000000e+00,4.366650e+04,4.366650e+04,-6.549975e+04,1.091662e+05,361
21,maximum_minimum_nights,2.000000e+00,3.000000e+01,2.800000e+01,-4.000000e+01,7.200000e+01,330
3,host_profile_id,1.462729e+18,1.469622e+18,6.892501e+15,1.452391e+18,1.479961e+18,301
13,bedrooms,1.000000e+00,2.000000e+00,1.000000e+00,-5.000000e-01,3.500000e+00,299
24,minimum_nights_avg_ntm,2.000000e+00,3.000000e+01,2.800000e+01,-4.000000e+01,7.200000e+01,170
20,minimum_minimum_nights,1.000000e+00,3.000000e+01,2.900000e+01,-4.250000e+01,7.350000e+01,152
18,minimum_nights,1.000000e+00,3.000000e+01,2.900000e+01,-4.250000e+01,7.350000e+01,152
47,calculated_host_listings_count_shared_rooms,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,79
23,maximum_maximum_nights,6.000000e+01,1.125000e+03,1.065000e+03,-1.537500e+03,2.722500e+03,27
19,maximum_nights,6.000000e+01,1.125000e+03,1.065000e+03,-1.537500e+03,2.722500e+03,27
25,maximum_nights_avg_ntm,4.252500e+01,1.125000e+03,1.082475e+03,-1.581187e+03,2.748712e+03,27
22,minimum_maximum_nights,2.800000e+01,1.125000e+03,1.097000e+03,-1.617500e+03,2.770500e+03,23
2,host_id,1.139554e+07,3.952601e+08,3.838645e+08,-5.644013e+08,9.710569e+08,12
6,hosts_time_as_host_years,3.000000e+00,1.000000e+01,7.000000e+00,-7.500000e+00,2.050000e+01,0
4,hosts_time_as_user_years,5.000000e+00,1.200000e+01,7.000000e+00,-5.500000e+00,2.250000e+01,0
7,hosts_time_as_host_months,3.000000e+00,8.000000e+00,5.000000e+00,-4.500000e+00,1.550000e+01,0
0,id,3.106840e+07,1.256909e+18,1.256909e+18,-1.885364e+18,3.142274e+18,0
1,scrape_id,2.026061e+13,2.026061e+13,0.000000e+00,2.026061e+13,2.026061e+13,0
9,latitude,3.775580e+01,3.778897e+01,3.317499e-02,3.770604e+01,3.783873e+01,0
5,hosts_time_as_user_months,3.000000e+00,8.000000e+00,5.000000e+00,-4.500000e+00,1.550000e+01,0
27,availability_60,0.000000e+00,3.400000e+01,3.400000e+01,-5.100000e+01,8.500000e+01,0
28,availability_90,3.000000e+00,5.900000e+01,5.600000e+01,-8.100000e+01,1.430000e+02,0
29,availability_365,5.200000e+01,3.010000e+02,2.490000e+02,-3.215000e+02,6.745000e+02,0
26,availability_30,0.000000e+00,1.400000e+01,1.400000e+01,-2.100000e+01,3.500000e+01,0
33,availability_eoy,2.800000e+01,1.530000e+02,1.250000e+02,-1.595000e+02,3.405000e+02,0
35,estimated_occupancy_l365d,0.000000e+00,1.800000e+02,1.800000e+02,-2.700000e+02,4.500000e+02,0

In [163]:
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'picture_url', 'host_id', 'host_url', 'host_profile_id',
       'host_profile_url', 'host_name', 'hosts_time_as_user_years',
       'hosts_time_as_user_months', 'hosts_time_as_host_years',
       'hosts_time_as_host_months', 'host_location', 'host_about',
       'host_is_superhost', 'host_picture_url', 'host_listings_count',
       'host_has_profile_pic', 'host_identity_verified',
       'neighbourhood_cleansed', 'latitude', 'longitude', 'property_type',
       'room_type', 'accommodates', 'bathrooms', 'bathrooms_text', 'bedrooms',
       'beds', 'amenities', 'price', 'price_quote_checkin_date',
       'price_quote_checkout_date', 'price_quote_total_price',
       'price_quote_price_per_night', 'price_quote_raw', 'minimum_nights',
       'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights',
       'minimum_maximum_nights', 'maximum_maximum_nights',
       'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'availability_eoy',
       'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month',
       'year_month', 'year', 'month'],
      dtype='str')

In [139]:
df

,id,listing_url,scrape_id,last_scraped,source,name,description,picture_url,host_id,host_url,...,review_scores_value,license,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,year_month,year,month
0,958,https://www.airbnb.com/rooms/958,20260614073227,2026-06-14,city scrape,"Bright, Modern Garden Unit - 1BR/1BTH",**Please note that the house behind our backya...,https://a0.muscache.com/pictures/be1bf5ac-a955...,1169,https://www.airbnb.com/users/show/1169,...,4.78,STR-0006854,1,1,0,0,2.58,2026-05,2026.0,5.0
1,5858,https://www.airbnb.com/rooms/5858,20260614073227,2026-06-14,city scrape,Creative Sanctuary,We live in a large Victorian house on a quiet ...,https://a0.muscache.com/pictures/hosting/Hosti...,8904,https://www.airbnb.com/users/show/8904,...,4.68,Unknown,1,1,0,0,0.5,2017-08,2017.0,8.0
2,8014,https://www.airbnb.com/rooms/8014,20260614073227,2026-06-14,city scrape,female HOST quiet fast internet market parking,Room is on the second floor so it gets a good ...,https://a0.muscache.com/pictures/2cc1fc3d-0ae0...,22402,https://www.airbnb.com/users/show/22402,...,4.67,STR-0000974,2,0,2,0,0.55,2026-06,2026.0,6.0
3,8142,https://www.airbnb.com/rooms/8142,20260614073227,2026-06-14,city scrape,*FriendlyRoom Apt. Style -UCSF/USF - San Franc...,Nice and good public transportation. 7 minute...,https://a0.muscache.com/pictures/hosting/Hosti...,21994,https://www.airbnb.com/users/show/21994,...,4.73,Unknown,22,0,22,0,0.08,2026-04,2026.0,4.0
4,8339,https://www.airbnb.com/rooms/8339,20260614073227,2026-06-22,previous scrape,Historic Alamo Square Victorian,"For creative humans who love art, space, photo...",https://a0.muscache.com/pictures/miso/Hosting-...,24215,https://www.airbnb.com/users/show/24215,...,4.75,STR-0000264,1,1,0,0,0.13,2019-06,2019.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7327,1706112761356045678,https://www.airbnb.com/rooms/1706112761356045678,20260614073227,2026-06-14,city scrape,1 Bedroom in SF,This stylish and unique place sets the stage f...,https://a0.muscache.com/pictures/hosting/Hosti...,67057435,https://www.airbnb.com/users/show/67057435,...,<NA>,Exempt,1,0,1,0,<NA>,NaT,NaN,NaN
7328,1706228944697932884,https://www.airbnb.com/rooms/1706228944697932884,20260614073227,2026-06-14,city scrape,A Tasteful and Elegant Home,"An elegant and comfortable home, thoughtfully ...",https://a0.muscache.com/pictures/hosting/Hosti...,542901530,https://www.airbnb.com/users/show/542901530,...,5.0,2026-004720STR,2,1,1,0,1.0,2026-06,2026.0,6.0
7329,1706229135493499688,https://www.airbnb.com/rooms/1706229135493499688,20260614073227,2026-06-14,city scrape,Luxury Modern Comfort Home,"Enjoy your own private lower-Level flat, thoug...",https://a0.muscache.com/pictures/hosting/Hosti...,542901530,https://www.airbnb.com/users/show/542901530,...,<NA>,2026-004720STR,2,1,1,0,<NA>,NaT,NaN,NaN
7330,1706477443981487094,https://www.airbnb.com/rooms/1706477443981487094,20260614073227,2026-06-14,city scrape,1BR Luxury Downtown | Bay Area,"A San Francisco landmark for over 70 years, th...",https://a0.muscache.com/pictures/hosting/Hosti...,179605934,https://www.airbnb.com/users/show/179605934,...,<NA>,Exempt,2,1,1,0,<NA>,NaT,NaN,NaN
7331,1706557052030067320,https://www.airbnb.com/rooms/1706557052030067320,20260614073227,2026-06-14,city scrape,Opera District Hotel | San Francisco,Soak up San Francisco’s dynamic arts culture a...,https://a0.muscache.com/pictures/hosting/Hosti...,179605934,https://www.airbnb.com/users/show/179605934,...,<NA>,Exempt,2,1,1,0,<NA>,NaT,NaN,NaN

### Visualize outliers with a box plot

In [189]:
box_cols = [
    "accommodates",
    "bathrooms",
    "bedrooms",
    "beds",
    "price",
    "price_quote_total_price",
    "price_quote_price_per_night",
    "minimum_nights",
    "maximum_nights",
    "availability_30",
    "availability_60",
    "availability_90",
    "availability_365",
    "number_of_reviews",
    "number_of_reviews_ltm",
    "number_of_reviews_l30d",
    "availability_eoy",
    "number_of_reviews_ly",
    "estimated_occupancy_l365d",
    "estimated_revenue_l365d",
    "review_scores_rating",
    "review_scores_accuracy",
    "review_scores_cleanliness",
    "review_scores_checkin",
    "review_scores_communication",
    "review_scores_location",
    "review_scores_value",
    "reviews_per_month"
]

In [190]:


for col in box_cols:
    fig = px.box(
        df,
        y=col,
        title=f"Box Plot: {col.title()}"
    )

    fig.show()

## Step 11 — Analyze relationships between numerical variables

**Ask:** use correlation

In [191]:
numeric_cols = [
    "accommodates",
    "bathrooms",
    "bedrooms",
    "beds",
    "price",
    "minimum_nights",
    "availability_365",
    "number_of_reviews",
    "estimated_occupancy_l365d",
    "estimated_revenue_l365d",
    "review_scores_rating",
    "reviews_per_month"
]

In [192]:
corr = df[numeric_cols].corr()

print(corr.round(2))

                           accommodates  bathrooms  bedrooms  beds  price  \
accommodates                       1.00       0.36      0.77  0.85   0.16
bathrooms                          0.36       1.00      0.46  0.37   0.09
bedrooms                           0.77       0.46      1.00  0.82   0.31
beds                               0.85       0.37      0.82  1.00   0.13
price                              0.16       0.09      0.31  0.13   1.00
minimum_nights                    -0.09       0.02      0.00 -0.09  -0.07
availability_365                   0.05       0.04     -0.00  0.02   0.04
number_of_reviews                 -0.07      -0.05     -0.08 -0.06  -0.04
estimated_occupancy_l365d         -0.08      -0.08     -0.03 -0.07  -0.08
estimated_revenue_l365d            0.24       0.08      0.24  0.23   0.09
review_scores_rating               0.06       0.00      0.08  0.06   0.09
reviews_per_month                 -0.00      -0.04     -0.09 -0.03  -0.04

                           minimum_nights  availability_365  \
accommodates                        -0.09              0.05
bathrooms                            0.02              0.04
bedrooms                             0.00             -0.00
beds                                -0.09              0.02
price                               -0.07              0.04
minimum_nights                       1.00              0.10
availability_365                     0.10              1.00
number_of_reviews                   -0.13             -0.01
estimated_occupancy_l365d           -0.12              0.05
estimated_revenue_l365d             -0.17             -0.12
review_scores_rating                -0.04             -0.16
reviews_per_month                   -0.17              0.04

                           number_of_reviews  estimated_occupancy_l365d  \
accommodates                           -0.07                      -0.08
bathrooms                              -0.05                      -0.08
bedrooms                               -0.08                      -0.03
beds                                   -0.06                      -0.07
price                                  -0.04                      -0.08
minimum_nights                         -0.13                      -0.12
availability_365                       -0.01                       0.05
number_of_reviews                       1.00                       0.54
estimated_occupancy_l365d               0.54                       1.00
estimated_revenue_l365d                 0.30                       0.62
review_scores_rating                    0.06                       0.10
reviews_per_month                       0.65                       0.54

                           estimated_revenue_l365d  review_scores_rating  \
accommodates                                  0.24                  0.06
bathrooms                                     0.08                  0.00
bedrooms                                      0.24                  0.08
beds                                          0.23                  0.06
price                                         0.09                  0.09
minimum_nights                               -0.17                 -0.04
availability_365                             -0.12                 -0.16
number_of_reviews                             0.30                  0.06
estimated_occupancy_l365d                     0.62                  0.10
estimated_revenue_l365d                       1.00                  0.17
review_scores_rating                          0.17                  1.00
reviews_per_month                             0.35                  0.05

                           reviews_per_month
accommodates                           -0.00
bathrooms                              -0.04
bedrooms                               -0.09
beds                                   -0.03
price                                  -0.04
minimum_nights                         -0.17
availability_365                        0.04
number_of_reviews                       0.65
estimated_occupancy_l365d               0.54
estimated_revenue_l365d                 0.35
review_scores_rating                    0.05
reviews_per_month                       1.00

In [167]:
correlation = numbers.corr()

correlation.round(2)

,id,scrape_id,host_id,host_profile_id,hosts_time_as_user_years,hosts_time_as_user_months,hosts_time_as_host_years,hosts_time_as_host_months,host_listings_count,latitude,...,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
id,1.00,NaN,0.07,0.30,-0.49,0.00,-0.58,-0.02,0.13,0.13,...,-0.04,-0.07,-0.08,-0.07,-0.04,0.04,0.01,0.03,-0.04,0.05
scrape_id,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
host_id,0.07,NaN,1.00,0.33,-0.08,-0.05,-0.07,-0.06,-0.01,-0.01,...,0.02,-0.00,0.01,0.02,0.02,-0.02,-0.01,-0.02,-0.00,0.01
host_profile_id,0.30,NaN,0.33,1.00,-0.27,-0.03,-0.34,-0.12,-0.05,0.00,...,0.03,0.01,0.01,0.02,0.04,-0.07,-0.06,-0.02,-0.02,0.07
hosts_time_as_user_years,-0.49,NaN,-0.08,-0.27,1.00,-0.01,0.75,-0.00,-0.20,-0.16,...,0.08,0.12,0.15,0.13,0.11,-0.13,-0.05,-0.14,0.00,-0.11
hosts_time_as_user_months,0.00,NaN,-0.05,-0.03,-0.01,1.00,-0.00,0.42,-0.09,-0.05,...,-0.04,-0.01,-0.01,0.01,-0.03,-0.08,-0.07,0.03,-0.00,-0.00
hosts_time_as_host_years,-0.58,NaN,-0.07,-0.34,0.75,-0.00,1.00,-0.04,-0.07,-0.08,...,0.00,0.05,0.06,0.08,0.01,0.03,0.07,-0.06,0.03,-0.14
hosts_time_as_host_months,-0.02,NaN,-0.06,-0.12,-0.00,0.42,-0.04,1.00,-0.09,-0.03,...,-0.03,-0.00,0.00,-0.02,0.01,-0.09,-0.08,0.00,0.01,0.01
host_listings_count,0.13,NaN,-0.01,-0.05,-0.20,-0.09,-0.07,-0.09,1.00,0.23,...,-0.00,-0.10,-0.20,-0.09,-0.09,0.76,0.74,0.01,-0.03,-0.10
latitude,0.13,NaN,-0.01,0.00,-0.16,-0.05,-0.08,-0.03,0.23,1.00,...,-0.02,-0.06,-0.07,0.06,-0.07,0.26,0.19,0.16,0.04,-0.11
longitude,0.11,NaN,-0.01,0.02,-0.08,-0.03,-0.04,-0.01,0.23,0.28,...,-0.01,-0.06,-0.07,-0.15,-0.05,0.26,0.22,0.08,-0.02,-0.17
accommodates,0.12,NaN,0.02,0.05,-0.09,-0.07,-0.10,-0.05,0.09,0.05,...,0.07,0.05,0.02,0.06,0.03,-0.01,-0.01,-0.11,-0.04,-0.00
bathrooms,0.08,NaN,-0.00,0.00,-0.01,0.01,-0.00,0.01,0.00,0.04,...,0.00,-0.03,-0.01,-0.02,-0.00,0.00,-0.02,0.03,0.10,-0.04
bedrooms,-0.01,NaN,0.01,-0.01,0.07,-0.04,0.05,-0.03,-0.07,-0.14,...,0.04,0.08,0.06,0.07,0.06,-0.10,-0.08,-0.11,-0.05,-0.09
beds,0.06,NaN,0.00,0.02,-0.03,-0.07,-0.03,-0.04,0.01,-0.00,...,0.05,0.06,0.04,0.05,0.03,-0.05,-0.05,-0.12,0.05,-0.03
price,0.02,NaN,0.01,0.01,-0.03,-0.02,-0.03,0.01,0.06,0.07,...,0.11,0.06,0.05,0.09,0.07,0.02,0.04,-0.04,-0.01,-0.04
price_quote_total_price,-0.04,NaN,-0.01,-0.02,0.09,-0.01,0.08,-0.01,-0.08,0.05,...,0.01,0.03,0.00,0.04,-0.00,-0.09,-0.03,-0.09,-0.03,-0.21
price_quote_price_per_night,0.02,NaN,0.01,0.01,-0.03,-0.02,-0.03,0.01,0.06,0.07,...,0.11,0.06,0.05,0.09,0.07,0.02,0.04,-0.04,-0.01,-0.04
minimum_nights,-0.13,NaN,-0.01,-0.04,0.07,-0.05,0.09,-0.04,-0.04,0.02,...,-0.11,-0.02,-0.03,-0.03,-0.06,0.05,-0.01,0.25,-0.03,-0.17
maximum_nights,-0.06,NaN,-0.00,-0.00,-0.02,-0.08,-0.01,-0.01,-0.01,0.04,...,0.00,-0.01,-0.03,0.01,-0.00,-0.01,-0.01,0.01,-0.01,-0.02
minimum_minimum_nights,-0.13,NaN,-0.01,-0.04,0.07,-0.05,0.09,-0.04,-0.04,0.02,...,-0.11,-0.02,-0.03,-0.03,-0.06,0.05,-0.01,0.25,-0.03,-0.17
maximum_minimum_nights,-0.09,NaN,-0.01,-0.05,0.04,-0.05,0.10,-0.04,0.28,0.06,...,-0.11,-0.07,-0.09,-0.07,-0.11,0.48,0.46,0.13,-0.03,-0.14
minimum_maximum_nights,-0.05,NaN,-0.00,-0.00,-0.02,-0.08,-0.01,0.00,-0.00,0.04,...,0.00,-0.01,-0.03,0.00,0.00,-0.01,-0.01,0.01,-0.00,-0.02
maximum_maximum_nights,-0.06,NaN,-0.00,-0.00,-0.02,-0.08,-0.01,-0.01,-0.01,0.04,...,0.00,-0.01,-0.03,0.01,-0.00,-0.01,-0.01,0.01,-0.01,-0.02
minimum_nights_avg_ntm,-0.12,NaN,-0.01,-0.03,0.05,-0.05,0.08,-0.04,-0.04,0.02,...,-0.09,-0.01,-0.02,-0.03,-0.05,0.06,0.01,0.22,-0.03,-0.16
maximum_nights_avg_ntm,-0.06,NaN,-0.00,-0.00,-0.02,-0.08,-0.01,-0.00,-0.01,0.04,...,0.00,-0.01,-0.03,0.01,0.00,-0.01,-0.01,0.01,-0.01,-0.02
availability_30,0.19,NaN,0.02,0.10,-0.23,-0.08,-0.17,-0.04,0.21,0.19,...,-0.02,-0.06,-0.07,-0.04,-0.06,0.01,-0.07,0.12,0.01,0.13
availability_60,0.20,NaN,0.02,0.10,-0.24,-0.06,-0.18,-0.03,0.21,0.16,...,-0.02,-0.06,-0.08,-0.05,-0.06,0.01,-0.06,0.10,0.01,0.17
availability_90,0.19,NaN,0.01,0.09,-0.24,-0.04,-0.17,-0.00,0.19,0.11,...,-0.06,-0.08,-0.10,-0.08,-0.09,-0.00,-0.07,0.10,-0.01,0.17
availability_365,0.16,NaN,0.01,0.05,-0.19,-0.00,-0.11,0.03,0.17,0.04,...,-0.15,-0.12,-0.13,-0.13,-0.14,0.04,-0.01,0.07,-0.04,0.04
number_of_reviews,-0.35,NaN,-0.02,-0.09,0.19,0.04,0.23,0.05,-0.14,-0.17,...,0.09,0.07,0.08,0.05,0.09,-0.17,-0.13,-0.10,0.03,0.65
number_of_reviews_ltm,-0.08,NaN,-0.02,-0.05,-0.01,0.01,-0.04,0.03,-0.13,-0.16,...,0.09,0.06,0.07,0.04,0.10,-0.17,-0.13,-0.11,0.02,0.85
number_of_reviews_l30d,-0.02,NaN,0.00,0.00,-0.02,-0.00,-0.06,0.02,-0.11,-0.13,...,0.07,0.03,0.04,0.04,0.08,-0.14,-0.11,-0.10,0.02,0.74
availability_eoy,0.15,NaN,0.00,0.06,-0.19,0.01,-0.13,0.03,0.15,0.02,...,-0.11,-0.10,-0.12,-0.12,-0.13,-0.01,-0.07,0.09,-0.03,0.12
number_of_reviews_ly,-0.13,NaN,-0.02,-0.07,0.01,0.01,-0.01,0.03,-0.13,-0.17,...,0.09,0.07,0.08,0.04,0.10,-0.17,-0.13,-0.11,0.01,0.77
estimated_occupancy_l365d,-0.19,NaN,-0.03,-0.10,0.11,0.05,0.04,0.06,-0.24,-0.26,...,0.10,0.10,0.12,0.06,0.12,-0.28,-0.23,-0.13,-0.02,0.54
estimated_revenue_l365d,-0.14,NaN,-0.03,-0.08,0.12,0.00,0.02,0.03,-0.15,-0.11,...,0.18,0.13,0.14,0.14,0.15,-0.25,-0.14,-0.19,-0.02,0.35
review_scores_rating,-0.06,NaN,0.02,0.02,0.14,-0.03,0.04,-0.02,-0.07,-0.05,...,0.74,0.72,0.75,0.55,0.80,-0.11,-0.03,-0.17,-0.03,0.05
review_scores_accuracy,-0.08,NaN,0.02,0.03,0.14,-0.02,0.05,0.00,-0.07,-0.05,...,0.70,0.67,0.67,0.48,0.76,-0.11,-0.03,-0.15,-0.01,0.07
review_scores_cleanliness,-0.04,NaN,0.02,0.03,0.08,-0.04,0.00,-0.03,-0.00,-0.02,...,1.00,0.56,0.55,0.43,0.68,-0.07,0.02,-0.20,-0.07,0.08
review_scores_checkin,-0.07,NaN,-0.00,0.01,0.12,-0.01,0.05,-0.00,-0.10,-0.06,...,0.56,1.00,0.71,0.46,0.61,-0.13,-0.08,-0.10,-0.01,0.05
review_scores_communication,-0.08,NaN,0.01,0.01,0.15,-0.01,0.06,0.00,-0.20,-0.07,...,0.55,0.71,1.00,0.43,0.64,-0.18,-0.14,-0.07,-0.02,0.06
review_scores_location,-0.07,NaN,0.02,0.02,0.13,0.01,0.08,-0.02,-0.09,0.06,...,0.43,0.46,0.43,1.00,0.54,-0.10,-0.05,-0.11,-0.00,0.03
review_scores_value,-0.04,NaN,0.02,0.04,0.11,-0.03,0.01,0.01,-0.09,-0.07,...,0.68,0.61,0.64,0.54,1.00,-0.15,-0.09,-0.14,-0.01,0.09
calculated_host_listings_count,0.04,NaN,-0.02,-0.07,-0.13,-0.08,0.03,-0.09,0.76,0.26,...,-0.07,-0.13,-0.18,-0.10,-0.15,1.00,0.94,0.19,0.00,-0.17
calculated_host_listings_count_entire_homes,0.01,NaN,-0.01,-0.06,-0.05,-0.07,0.07,-0.08,0.74,0.19,...,0.02,-0.08,-0.14,-0.05,-0.09,0.94,1.00,-0.12,-0.03,-0.13
calculated_host_listings_count_private_rooms,0.03,NaN,-0.02,-0.02,-0.14,0.03,-0.06,0.00,0.01,0.16,...,-0.20,-0.10,-0.07,-0.11,-0.14,0.19,-0.12,1.00,0.06,-0.10
calculated_host_listings_count_shared_rooms,-0.04,NaN,-0.00,-0.02,0.00,-0.00,0.03,0.01,-0.03,0.04,...,-0.07,-0.01,-0.02,-0.00,-0.01,0.00,-0.03,0.06,1.00,0.01
reviews_per_month,0.05,NaN,0.01,0.07,-0.11,-0.00,-0.14,0.01,-0.10,-0.11,...,0.08,0.05,0.06,0.03,0.09,-0.17,-0.13,-0.10,0.01,1.00

In [194]:
fig = px.scatter_matrix(
    df,
    dimensions=numeric_cols,
    title="Scatter Matrix of Numeric Variables"
)

fig.show()

In [195]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7332 entries, 0 to 7331
Data columns (total 80 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            7332 non-null   Int64
 1   listing_url                                   7332 non-null   str
 2   scrape_id                                     7332 non-null   Int64
 3   last_scraped                                  7332 non-null   datetime64[us]
 4   source                                        7332 non-null   str
 5   name                                          7332 non-null   str
 6   description                                   7332 non-null   str
 7   picture_url                                   7332 non-null   str
 8   host_id                                       7332 non-null   Int64
 9   host_url                                      7332 non-null   str
 10  host_profile_id                               7242 non-null   Int64
 11  host_profile_url                              7332 non-null   str
 12  host_name                                     7332 non-null   str
 13  hosts_time_as_user_years                      7242 non-null   Int64
 14  hosts_time_as_user_months                     7242 non-null   Int64
 15  hosts_time_as_host_years                      7242 non-null   Int64
 16  hosts_time_as_host_months                     7242 non-null   Int64
 17  host_location                                 7332 non-null   str
 18  host_about                                    7332 non-null   str
 19  host_is_superhost                             7332 non-null   str
 20  host_picture_url                              7332 non-null   str
 21  host_listings_count                           7242 non-null   Int64
 22  host_has_profile_pic                          7332 non-null   str
 23  host_identity_verified                        7332 non-null   str
 24  neighbourhood_cleansed                        7332 non-null   str
 25  latitude                                      7332 non-null   Float64
 26  longitude                                     7332 non-null   Float64
 27  property_type                                 7332 non-null   str
 28  room_type                                     7332 non-null   str
 29  accommodates                                  7332 non-null   Int64
 30  bathrooms                                     5406 non-null   Float64
 31  bathrooms_text                                7332 non-null   str
 32  bedrooms                                      5341 non-null   Int64
 33  beds                                          5635 non-null   Int64
 34  amenities                                     7332 non-null   str
 35  price                                         5932 non-null   Float64
 36  price_quote_checkin_date                      6196 non-null   datetime64[us]
 37  price_quote_checkout_date                     6196 non-null   datetime64[us]
 38  price_quote_total_price                       5932 non-null   Float64
 39  price_quote_price_per_night                   5932 non-null   Float64
 40  price_quote_raw                               7332 non-null   str
 41  minimum_nights                                7328 non-null   Int64
 42  maximum_nights                                7328 non-null   Int64
 43  minimum_minimum_nights                        7328 non-null   Int64
 44  maximum_minimum_nights                        7328 non-null   Int64
 45  minimum_maximum_nights                        7328 non-null   Int64
 46  maximum_maximum_nights                        7328 non-null   Int64
 47  minimum_nights_avg_ntm                        7332 non-null   Float64
 48  maximum_nights_avg_ntm                        7332 non-null   Float64
 49  has_availability                              7332 non-null   str
 50  availability_30                               7332 non-null   Int64
 51  availability_60                               7332 non-null   Int64
 52  availability_90                               7332 non-null   Int64
 53  availability_365                              7332 non-null   Int64
 54  calendar_last_scraped                         7332 non-null   datetime64[us]
 55  number_of_reviews                             7332 non-null   Int64
 56  number_of_reviews_ltm                         7332 non-null   Int64
 57  number_of_reviews_l30d                        7332 non-null   Int64
 58  availability_eoy                              7332 non-null   Int64
 59  number_of_reviews_ly                          7332 non-null   Int64
 60  estimated_occupancy_l365d                     7332 non-null   Int64
 61  estimated_revenue_l365d                       5932 non-null   Int64
 62  first_review                                  5748 non-null   datetime64[us]
 63  last_review                                   5748 non-null   datetime64[us]
 64  review_scores_rating                          5748 non-null   Float64
 65  review_scores_accuracy                        5747 non-null   Float64
 66  review_scores_cleanliness                     5747 non-null   Float64
 67  review_scores_checkin                         5746 non-null   Float64
 68  review_scores_communication                   5747 non-null   Float64
 69  review_scores_location                        5746 non-null   Float64
 70  review_scores_value                           5746 non-null   Float64
 71  license                                       7332 non-null   str
 72  calculated_host_listings_count                7332 non-null   Int64
 73  calculated_host_listings_count_entire_homes   7332 non-null   Int64
 74  calculated_host_listings_count_private_rooms  7332 non-null   Int64
 75  calculated_host_listings_count_shared_rooms   7332 non-null   Int64
 76  reviews_per_month                             5748 non-null   Float64
 77  year_month                                    5748 non-null   period[M]
 78  year                                          5748 non-null   float64
 79  month                                         5748 non-null   float64
dtypes: Float64(16), Int64(33), datetime64[us](6), float64(2), period[M](1), str(22)
memory usage: 4.8 MB

## Step 12 — Compare performance across groups

**Ask:** use Groupby

In [215]:
df.groupby("room_type")[
    ["price", "number_of_reviews", "estimated_occupancy_l365d", "estimated_revenue_l365d"]
].mean().round(2)

,price,number_of_reviews,estimated_occupancy_l365d,estimated_revenue_l365d
room_type,,,,
Entire home/apt,457.1,56.38,93.73,41316.99
Hotel room,575.85,17.91,22.03,9599.63
Private room,330.25,66.61,86.87,17676.38
Shared room,97.32,167.79,126.24,13808.95

In [216]:
df.groupby("room_type")["review_scores_rating"].mean().round(2)

room_type
Entire home/apt    4.84
Hotel room         4.48
Private room       4.75
Shared room        4.72
Name: review_scores_rating, dtype: Float64

In [217]:
df.groupby("room_type")[
    [
        "price",
        "estimated_occupancy_l365d",
        "estimated_revenue_l365d",
        "review_scores_rating"
    ]
].mean().round(2)

,price,estimated_occupancy_l365d,estimated_revenue_l365d,review_scores_rating
room_type,,,,
Entire home/apt,457.1,93.73,41316.99,4.84
Hotel room,575.85,22.03,9599.63,4.48
Private room,330.25,86.87,17676.38,4.75
Shared room,97.32,126.24,13808.95,4.72

In [218]:
df.groupby("property_type")["price"].mean().round(2)

property_type
Campsite                                582.0
Casa particular                         342.5
Entire bungalow                        522.44
Entire cabin                           171.96
Entire condo                           518.13
Entire cottage                         286.36
Entire guest suite                     296.01
Entire guesthouse                      296.22
Entire home                            661.49
Entire in-law                           220.0
Entire loft                            324.84
Entire place                           542.92
Entire rental unit                     347.13
Entire resort                          394.55
Entire serviced apartment              398.92
Entire townhouse                      1182.77
Entire vacation home                   398.43
Entire villa                          2597.24
Private room                           191.13
Private room in bed and breakfast      576.24
Private room in bungalow                 <NA>
Private room in casa particular         69.14
Private room in condo                  296.56
Private room in cottage                462.77
Private room in guest suite            195.71
Private room in guesthouse             165.67
Private room in home                   157.98
Private room in hostel                 196.83
Private room in loft                   124.77
Private room in rental unit            135.11
Private room in resort                 561.75
Private room in serviced apartment     125.21
Private room in townhouse               194.5
Private room in villa                    <NA>
Room in aparthotel                     271.42
Room in bed and breakfast              634.33
Room in boutique hotel                1437.12
Room in hostel                          171.5
Room in hotel                          530.44
Room in serviced apartment              322.5
Shared room in bed and breakfast        50.33
Shared room in boutique hotel            63.0
Shared room in condo                   451.33
Shared room in home                     46.47
Shared room in hostel                    67.2
Shared room in hotel                     68.8
Shared room in loft                     168.2
Shared room in rental unit             128.83
Tiny home                              130.49
Name: price, dtype: Float64

In [219]:
df.groupby("property_type")["estimated_revenue_l365d"].mean().round(2)

property_type
Campsite                                 6402.0
Casa particular                         87338.0
Entire bungalow                        51862.67
Entire cabin                            41270.0
Entire condo                           31189.95
Entire cottage                          55118.8
Entire guest suite                     58014.48
Entire guesthouse                      47568.09
Entire home                            65234.87
Entire in-law                           56100.0
Entire loft                            39029.36
Entire place                           107633.5
Entire rental unit                     28755.67
Entire resort                          10378.61
Entire serviced apartment               14914.0
Entire townhouse                       59870.05
Entire vacation home                    5730.67
Entire villa                          103279.44
Private room                           38628.25
Private room in bed and breakfast       8118.52
Private room in bungalow                   <NA>
Private room in casa particular             0.0
Private room in condo                  29564.93
Private room in cottage                18749.67
Private room in guest suite            35393.35
Private room in guesthouse             24311.33
Private room in home                   21061.83
Private room in hostel                  16258.0
Private room in loft                   23859.83
Private room in rental unit            13577.13
Private room in resort                  2548.62
Private room in serviced apartment      10403.4
Private room in townhouse              26865.33
Private room in villa                      <NA>
Room in aparthotel                     28131.34
Room in bed and breakfast                   0.0
Room in boutique hotel                 15451.92
Room in hostel                          21248.0
Room in hotel                          12039.66
Room in serviced apartment                  0.0
Shared room in bed and breakfast        12835.0
Shared room in boutique hotel           16065.0
Shared room in condo                    19859.0
Shared room in home                      8365.0
Shared room in hostel                    7734.4
Shared room in hotel                    14151.0
Shared room in loft                         0.0
Shared room in rental unit              27986.0
Tiny home                               13643.0
Name: estimated_revenue_l365d, dtype: Float64

In [220]:
df.groupby("room_type")["id"].count()

room_type
Entire home/apt    4477
Hotel room          243
Private room       2579
Shared room          33
Name: id, dtype: Int64

In [221]:
df

,id,listing_url,scrape_id,last_scraped,source,name,description,picture_url,host_id,host_url,...,review_scores_value,license,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,year_month,year,month
0,958,https://www.airbnb.com/rooms/958,20260614073227,2026-06-14,city scrape,"Bright, Modern Garden Unit - 1BR/1BTH",**Please note that the house behind our backya...,https://a0.muscache.com/pictures/be1bf5ac-a955...,1169,https://www.airbnb.com/users/show/1169,...,4.78,STR-0006854,1,1,0,0,2.58,2026-05,2026.0,5.0
1,5858,https://www.airbnb.com/rooms/5858,20260614073227,2026-06-14,city scrape,Creative Sanctuary,We live in a large Victorian house on a quiet ...,https://a0.muscache.com/pictures/hosting/Hosti...,8904,https://www.airbnb.com/users/show/8904,...,4.68,Unknown,1,1,0,0,0.5,2017-08,2017.0,8.0
2,8014,https://www.airbnb.com/rooms/8014,20260614073227,2026-06-14,city scrape,female HOST quiet fast internet market parking,Room is on the second floor so it gets a good ...,https://a0.muscache.com/pictures/2cc1fc3d-0ae0...,22402,https://www.airbnb.com/users/show/22402,...,4.67,STR-0000974,2,0,2,0,0.55,2026-06,2026.0,6.0
3,8142,https://www.airbnb.com/rooms/8142,20260614073227,2026-06-14,city scrape,*FriendlyRoom Apt. Style -UCSF/USF - San Franc...,Nice and good public transportation. 7 minute...,https://a0.muscache.com/pictures/hosting/Hosti...,21994,https://www.airbnb.com/users/show/21994,...,4.73,Unknown,22,0,22,0,0.08,2026-04,2026.0,4.0
4,8339,https://www.airbnb.com/rooms/8339,20260614073227,2026-06-22,previous scrape,Historic Alamo Square Victorian,"For creative humans who love art, space, photo...",https://a0.muscache.com/pictures/miso/Hosting-...,24215,https://www.airbnb.com/users/show/24215,...,4.75,STR-0000264,1,1,0,0,0.13,2019-06,2019.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7327,1706112761356045678,https://www.airbnb.com/rooms/1706112761356045678,20260614073227,2026-06-14,city scrape,1 Bedroom in SF,This stylish and unique place sets the stage f...,https://a0.muscache.com/pictures/hosting/Hosti...,67057435,https://www.airbnb.com/users/show/67057435,...,<NA>,Exempt,1,0,1,0,<NA>,NaT,NaN,NaN
7328,1706228944697932884,https://www.airbnb.com/rooms/1706228944697932884,20260614073227,2026-06-14,city scrape,A Tasteful and Elegant Home,"An elegant and comfortable home, thoughtfully ...",https://a0.muscache.com/pictures/hosting/Hosti...,542901530,https://www.airbnb.com/users/show/542901530,...,5.0,2026-004720STR,2,1,1,0,1.0,2026-06,2026.0,6.0
7329,1706229135493499688,https://www.airbnb.com/rooms/1706229135493499688,20260614073227,2026-06-14,city scrape,Luxury Modern Comfort Home,"Enjoy your own private lower-Level flat, thoug...",https://a0.muscache.com/pictures/hosting/Hosti...,542901530,https://www.airbnb.com/users/show/542901530,...,<NA>,2026-004720STR,2,1,1,0,<NA>,NaT,NaN,NaN
7330,1706477443981487094,https://www.airbnb.com/rooms/1706477443981487094,20260614073227,2026-06-14,city scrape,1BR Luxury Downtown | Bay Area,"A San Francisco landmark for over 70 years, th...",https://a0.muscache.com/pictures/hosting/Hosti...,179605934,https://www.airbnb.com/users/show/179605934,...,<NA>,Exempt,2,1,1,0,<NA>,NaT,NaN,NaN
7331,1706557052030067320,https://www.airbnb.com/rooms/1706557052030067320,20260614073227,2026-06-14,city scrape,Opera District Hotel | San Francisco,Soak up San Francisco’s dynamic arts culture a...,https://a0.muscache.com/pictures/hosting/Hosti...,179605934,https://www.airbnb.com/users/show/179605934,...,<NA>,Exempt,2,1,1,0,<NA>,NaT,NaN,NaN

In [222]:
df.groupby("room_type")["estimated_revenue_l365d"].max()

room_type
Entire home/apt    531076
Hotel room         237405
Private room       359976
Shared room         58268
Name: estimated_revenue_l365d, dtype: Int64

In [223]:
df.groupby("room_type")["estimated_revenue_l365d"].min()

room_type
Entire home/apt    0
Hotel room         0
Private room       0
Shared room        0
Name: estimated_revenue_l365d, dtype: Int64

In [224]:
df.groupby("neighbourhood_cleansed")["number_of_reviews"].mean().round(2)

neighbourhood_cleansed
Bayview                   59.11
Bernal Heights            89.55
Castro/Upper Market       95.72
Chinatown                 37.56
Crocker Amazon            75.34
Diamond Heights            66.2
Downtown/Civic Center     16.74
Excelsior                 75.16
Financial District        32.16
Glen Park                 65.76
Golden Gate Park          166.0
Haight Ashbury            78.14
Inner Richmond            82.57
Inner Sunset              83.38
Lakeshore                 78.88
Marina                    63.86
Mission                    65.2
Nob Hill                  20.17
Noe Valley                70.55
North Beach                24.0
Ocean View                56.14
Outer Mission             80.98
Outer Richmond           112.07
Outer Sunset             128.99
Pacific Heights           63.79
Parkside                  106.1
Potrero Hill             108.26
Presidio                  42.96
Presidio Heights          88.81
Russian Hill              34.23
Seacliff                  78.86
South of Market           26.74
Twin Peaks                 93.4
Visitacion Valley        127.47
West of Twin Peaks       123.62
Western Addition          64.78
Name: number_of_reviews, dtype: Float64

In [225]:
df

,id,listing_url,scrape_id,last_scraped,source,name,description,picture_url,host_id,host_url,...,review_scores_value,license,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,year_month,year,month
0,958,https://www.airbnb.com/rooms/958,20260614073227,2026-06-14,city scrape,"Bright, Modern Garden Unit - 1BR/1BTH",**Please note that the house behind our backya...,https://a0.muscache.com/pictures/be1bf5ac-a955...,1169,https://www.airbnb.com/users/show/1169,...,4.78,STR-0006854,1,1,0,0,2.58,2026-05,2026.0,5.0
1,5858,https://www.airbnb.com/rooms/5858,20260614073227,2026-06-14,city scrape,Creative Sanctuary,We live in a large Victorian house on a quiet ...,https://a0.muscache.com/pictures/hosting/Hosti...,8904,https://www.airbnb.com/users/show/8904,...,4.68,Unknown,1,1,0,0,0.5,2017-08,2017.0,8.0
2,8014,https://www.airbnb.com/rooms/8014,20260614073227,2026-06-14,city scrape,female HOST quiet fast internet market parking,Room is on the second floor so it gets a good ...,https://a0.muscache.com/pictures/2cc1fc3d-0ae0...,22402,https://www.airbnb.com/users/show/22402,...,4.67,STR-0000974,2,0,2,0,0.55,2026-06,2026.0,6.0
3,8142,https://www.airbnb.com/rooms/8142,20260614073227,2026-06-14,city scrape,*FriendlyRoom Apt. Style -UCSF/USF - San Franc...,Nice and good public transportation. 7 minute...,https://a0.muscache.com/pictures/hosting/Hosti...,21994,https://www.airbnb.com/users/show/21994,...,4.73,Unknown,22,0,22,0,0.08,2026-04,2026.0,4.0
4,8339,https://www.airbnb.com/rooms/8339,20260614073227,2026-06-22,previous scrape,Historic Alamo Square Victorian,"For creative humans who love art, space, photo...",https://a0.muscache.com/pictures/miso/Hosting-...,24215,https://www.airbnb.com/users/show/24215,...,4.75,STR-0000264,1,1,0,0,0.13,2019-06,2019.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7327,1706112761356045678,https://www.airbnb.com/rooms/1706112761356045678,20260614073227,2026-06-14,city scrape,1 Bedroom in SF,This stylish and unique place sets the stage f...,https://a0.muscache.com/pictures/hosting/Hosti...,67057435,https://www.airbnb.com/users/show/67057435,...,<NA>,Exempt,1,0,1,0,<NA>,NaT,NaN,NaN
7328,1706228944697932884,https://www.airbnb.com/rooms/1706228944697932884,20260614073227,2026-06-14,city scrape,A Tasteful and Elegant Home,"An elegant and comfortable home, thoughtfully ...",https://a0.muscache.com/pictures/hosting/Hosti...,542901530,https://www.airbnb.com/users/show/542901530,...,5.0,2026-004720STR,2,1,1,0,1.0,2026-06,2026.0,6.0
7329,1706229135493499688,https://www.airbnb.com/rooms/1706229135493499688,20260614073227,2026-06-14,city scrape,Luxury Modern Comfort Home,"Enjoy your own private lower-Level flat, thoug...",https://a0.muscache.com/pictures/hosting/Hosti...,542901530,https://www.airbnb.com/users/show/542901530,...,<NA>,2026-004720STR,2,1,1,0,<NA>,NaT,NaN,NaN
7330,1706477443981487094,https://www.airbnb.com/rooms/1706477443981487094,20260614073227,2026-06-14,city scrape,1BR Luxury Downtown | Bay Area,"A San Francisco landmark for over 70 years, th...",https://a0.muscache.com/pictures/hosting/Hosti...,179605934,https://www.airbnb.com/users/show/179605934,...,<NA>,Exempt,2,1,1,0,<NA>,NaT,NaN,NaN
7331,1706557052030067320,https://www.airbnb.com/rooms/1706557052030067320,20260614073227,2026-06-14,city scrape,Opera District Hotel | San Francisco,Soak up San Francisco’s dynamic arts culture a...,https://a0.muscache.com/pictures/hosting/Hosti...,179605934,https://www.airbnb.com/users/show/179605934,...,<NA>,Exempt,2,1,1,0,<NA>,NaT,NaN,NaN

In [226]:
df.groupby("host_is_superhost")[
    [
        "price",
        "number_of_reviews",
        "review_scores_rating",
        "estimated_occupancy_l365d",
        "estimated_revenue_l365d"
    ]
].mean().round(2)

,price,number_of_reviews,review_scores_rating,estimated_occupancy_l365d,estimated_revenue_l365d
host_is_superhost,,,,,
Unknown,332.72,17.1,4.49,46.38,12850.26
f,441.3,31.2,4.71,52.46,17610.19
t,389.34,91.53,4.89,131.03,45346.29

## Step 13 — Time-series EDA

**Ask:** what is trend over time? Are some months stronger than others?

In [227]:
df["year_month"] = df["last_review"].dt.to_period("M")

monthly_trend = (
    df.groupby("year_month")["number_of_reviews"]
      .sum()
)

print(monthly_trend)

year_month
2012-06        48
2012-11         5
2014-03        16
2014-08        10
2014-09        99
            ...
2026-02      7828
2026-03     15019
2026-04     19986
2026-05    159188
2026-06    178462
Freq: M, Name: number_of_reviews, Length: 135, dtype: Int64

In [228]:
df["year_month"] = df["last_review"].dt.to_period("M")

monthly_trend = (
    df.groupby("year_month")["number_of_reviews"]
      .sum()
)

print(monthly_trend)

year_month
2012-06        48
2012-11         5
2014-03        16
2014-08        10
2014-09        99
            ...
2026-02      7828
2026-03     15019
2026-04     19986
2026-05    159188
2026-06    178462
Freq: M, Name: number_of_reviews, Length: 135, dtype: Int64

In [229]:
monthly_revenue = (
    df.groupby("year_month")["estimated_revenue_l365d"]
      .sum()
)


monthly_price = (
    df.groupby("year_month")["price"]
      .mean()
      .round(2)
)

df["year"] = df["last_review"].dt.year

yearly_reviews = (
    df.groupby("year")["number_of_reviews"]
      .mean()
      .round(2)
)

print("\nAverage reviews by year:")
print(yearly_reviews)
print("\nEstimated revenue by month:")
print(monthly_revenue)
print("\nAverage price by month:")
print(monthly_price)

Average reviews by year:
year
2012.0      26.5
2014.0     14.89
2015.0     21.09
2016.0      8.88
2017.0     29.31
2018.0     24.07
2019.0     19.84
2020.0      35.4
2021.0     16.46
2022.0     13.99
2023.0     18.23
2024.0     16.42
2025.0     26.54
2026.0    105.53
Name: number_of_reviews, dtype: Float64

Estimated revenue by month:
year_month
2012-06           0
2012-11           0
2014-03           0
2014-08           0
2014-09           0
             ...
2026-02     6003794
2026-03    10024778
2026-04    14629653
2026-05    72355629
2026-06    67379829
Freq: M, Name: estimated_revenue_l365d, Length: 135, dtype: Int64

Average price by month:
year_month
2012-06     89.22
2012-11    118.73
2014-03    134.11
2014-08     191.1
2014-09     48.12
            ...
2026-02    576.83
2026-03    368.46
2026-04    330.64
2026-05     332.6
2026-06    348.66
Freq: M, Name: price, Length: 135, dtype: Float64

In [230]:
monthly_listings = (
    df.groupby("year_month")["id"]
      .count()
)



df["month"] = df["last_review"].dt.month

month_strength = (
    df.groupby("month")["number_of_reviews"]
      .mean()
      .round(2)
)

print("\nNumber of listings reviewed each month:")
print(monthly_listings)
print("\nAverage reviews by month of year:")
print(month_strength)

Number of listings reviewed each month:
year_month
2012-06       1
2012-11       1
2014-03       2
2014-08       1
2014-09       2
           ...
2026-02     216
2026-03     394
2026-04     419
2026-05    1397
2026-06    1030
Freq: M, Name: id, Length: 135, dtype: Int64

Average reviews by month of year:
month
1.0      25.45
2.0      34.53
3.0       34.8
4.0       42.8
5.0     104.47
6.0     158.44
7.0      24.39
8.0      20.15
9.0      21.36
10.0     18.46
11.0     28.32
12.0     33.22
Name: number_of_reviews, dtype: Float64

## Step 14 — Find the best and worst performers

A useful EDA habit is to inspect both extremes rather than only averages.

In [231]:
col = [
    "id",
    "name",
    "room_type",
    "price",
    "estimated_revenue_l365d"
]

#by revenue
best_revenue = df.sort_values(
    "estimated_revenue_l365d",
    ascending=False
).head(10)

worst_revenue = df.sort_values(
    "estimated_revenue_l365d",
    ascending=True
).head(10)

print("TOP 10 — Highest Revenue")
print(best_revenue[col])

print("\nBOTTOM 10 — Lowest Revenue")
print(worst_revenue[col])


#by rating
best_rating = df.sort_values(
    "review_scores_rating",
    ascending=False
).head(10)

worst_rating = df.sort_values(
    "review_scores_rating",
    ascending=True
).head(10)

print("\nTOP 10 — Highest Rating")
print(best_rating[col])

print("\nBOTTOM 10 — Lowest Rating")
print(worst_rating[col])

TOP 10 — Highest Revenue
                       id                                               name  \
804               8864274                   Classic Elegance Pacific Heights
1330             19721174  The Linden - Private Modern Oasis in Hayes Valley
4740  1024755875429155314                 Serene 3 Bedroom House with Garden
5864  1353886845180944662                                 Hayes Valley Haven
4516   955995067181069574         Spacious and elegant Presidio Heights home
3261             54020696                         Ultra Swanky Designer Home
249               1212746  Large 3BR SF Home! Families, Friends or Collea...
5162  1150035165322217918       4Br4Ba Spacious | Movie & Game Room + Garage
1476             22555972     The Painted Man- SF Historic Victorian Mansion
638               6188428             SF Fishermans Wharf Bay View Penthouse

            room_type    price  estimated_revenue_l365d
804   Entire home/apt  2082.65                   531076
1330  Entire home/apt   4736.0                   468864
4740  Entire home/apt   1777.0                   453135
5864  Entire home/apt   1755.0                   447525
4516  Entire home/apt   2168.5                   429363
3261  Entire home/apt   7133.0                   392315
249   Entire home/apt   1697.0                   392007
5162  Entire home/apt   1464.0                   373320
1476     Private room  2181.67                   359976
638      Private room   1710.4                   357474

BOTTOM 10 — Lowest Revenue
                       id                                              name  \
7298  1698706970487904312                1BD/1BA Presidential at Canterbury
49                  78651                    Heart of the Mission: Hot spot
2537             42429868  #aQ15 Sunny room for 1-2 near Downtown (NobHill)
7310  1700214892202467757                                      Studio in SF
7309  1700156745579183986   Cozy North Beach Apartment with Coit Tower View
7308  1699552620377621218  Luxury City Residence 3BR | Ritz-Carlton Club SF
7307  1699356851383035959                           Studio at The Donatello
7306  1699352089481964702                      2BD/1BA at Fisherman's Wharf
7305  1699347761768174968                      1BD/1BA at Fisherman's Wharf
7304  1699339206007769032                    Hotel Room at Inn at the Opera

            room_type   price  estimated_revenue_l365d
7298     Private room   503.5                        0
49       Private room   84.08                        0
2537     Private room    5.28                        0
7310     Private room  855.89                        0
7309  Entire home/apt   279.5                        0
7308  Entire home/apt  2511.0                        0
7307     Private room   343.5                        0
7306     Private room   419.0                        0
7305     Private room   330.0                        0
7304     Private room   286.5                        0

TOP 10 — Highest Rating
                       id                                               name  \
7190  1666807450212374619   Sunny Mission Room with Private Bath • Near BART
7328  1706228944697932884                        A Tasteful and Elegant Home
2968             50338646     Residential hotel near Union Square SF room#12
2969             50350639                       Private oasis in SF downtown
2979             50489368  (B) Furnished Efficiency Studio near Union Square
2981             50509087       Stunning luxury condo with best views in SF!
2950             50169742     79b SFSU/Parkside spacious masterstew/ocean vw
2955             50207641      24 C -Beautiful lakeshore entire APT. 2bd/2ba
2956             50212186            Artist's Private Mission Garden Cottage
2957             50216842  Castro: Garden retreat, home office, parking, ...

            room_type   price  estimated_revenue_l365d
7190     Private room  182.59                     4017
7328     Private room   224.0                     2464
2968     Private room   70.65                     4522
2969  Entire home/apt    <NA>                     <NA>
2979  Entire home/apt    <NA>                     <NA>
2981  Entire home/apt   608.4                        0
2950     Private room    84.1                    20184
2955  Entire home/apt   856.0                     9416
2956  Entire home/apt  204.97                    52267
2957  Entire home/apt    <NA>                     <NA>

BOTTOM 10 — Lowest Rating
                       id                                         name  \
6130  1415340595712585603             2 Bedrooms Unit Golden Gate Park
6140  1416208886986493175                  Bright Modern 2BR Apt in SF
6182  1427057282418287489               SOMA ROOMS w/ Shared bathrooms
6461  1495364213823610799      Private Room near Golden Gate Park UCSF
4645   993560474088542942                Beautiful Studio Hayes Valley
6568  1524024128780261354                 Union Square Work Trip Suite
4522   957700174353441802                    Bush Street Boutique Stay
5458  1243631964701808950                  Cornell Hotel, Deluxe queen
1796             30368366  Blueground | S. Beach, pool, next to SF bay
6082  1408424976810441280             Room 5min walkto City College SF

            room_type   price  estimated_revenue_l365d
6130  Entire home/apt    <NA>                     <NA>
6140  Entire home/apt   173.4                    20808
6182     Private room    54.6                     3276
6461     Private room   83.85                     5031
4645  Entire home/apt  100.94                        0
6568     Private room   117.0                     1287
4522  Entire home/apt  137.34                        0
5458     Private room   160.0                     1760
1796  Entire home/apt    <NA>                     <NA>
6082     Private room   48.76                     2926

In [232]:
df['description']

0       **Please note that the house behind our backya...
1       We live in a large Victorian house on a quiet ...
2       Room is on the second floor so it gets a good ...
3       Nice and good public transportation.  7 minute...
4       For creative humans who love art, space, photo...
                              ...
7327    This stylish and unique place sets the stage f...
7328    An elegant and comfortable home, thoughtfully ...
7329    Enjoy your own private lower-Level flat, thoug...
7330    A San Francisco landmark for over 70 years, th...
7331    Soak up San Francisco’s dynamic arts culture a...
Name: description, Length: 7332, dtype: str

## Step 15 — Business questions

Try answering these from the analysis above:

1. Which region generates the highest sales?
2. Which region generates the highest profit?
3. Which category generates the highest sales?
4. Which category is most profitable?
5. Does higher discount appear to reduce profitability?
6. Which orders are unusually large?
7. Are high-sales orders always high-profit orders?
8. Which month has the highest sales?
9. Which customer segment contributes the most revenue?
10. What data-quality issues did we discover?

In [233]:
# 1. Highest-revenue neighbourhood
neighbourhood_revenue = (
    df.groupby("neighbourhood_cleansed")["estimated_revenue_l365d"]
      .sum()
      .sort_values(ascending=False)
)

print("1. Highest-revenue neighbourhood:")
print(neighbourhood_revenue.head(10))


# 2. Highest average revenue by neighbourhood
print("\n2. Highest average revenue:")
print(
    df.groupby("neighbourhood_cleansed")["estimated_revenue_l365d"]
      .mean()
      .sort_values(ascending=False)
      .head(10)
)


# 3. Highest-revenue property type
print("\n3. Highest-revenue property type:")
print(
    df.groupby("property_type")["estimated_revenue_l365d"]
      .sum()
      .sort_values(ascending=False)
)


# 4. Most profitable category proxy
print("\n4. Highest average revenue by property type:")
print(
    df.groupby("property_type")["estimated_revenue_l365d"]
      .mean()
      .sort_values(ascending=False)
)


# 5. Discount vs profitability
print("\n5. Discount:")
print("Cannot answer — no discount column exists.")


# 6. Unusually large listings
threshold = df["estimated_revenue_l365d"].quantile(0.95)

large_listings = df[
    df["estimated_revenue_l365d"] >= threshold
]

print("\n6. Unusually large listings:")
print(large_listings[[
    "id",
    "name",
    "price",
    "estimated_revenue_l365d"
]].head(20))


# 7. Price vs revenue relationship
print("\n7. Price vs revenue correlation:")
print(
    df[["price", "estimated_revenue_l365d"]].corr()
)


# 8. Strongest month by review activity
df["month"] = df["last_review"].dt.month

monthly_reviews = (
    df.groupby("month")["number_of_reviews"]
      .sum()
      .sort_values(ascending=False)
)

print("\n8. Strongest month:")
print(monthly_reviews)


# 9. Highest-revenue room type
print("\n9. Highest-revenue room type:")
print(
    df.groupby("room_type")["estimated_revenue_l365d"]
      .sum()
      .sort_values(ascending=False)
)


# 10. Data-quality issues
print("\n10. Data-quality issues:")
print(df.isna().sum().sort_values(ascending=False).head(20))

1. Highest-revenue neighbourhood:
neighbourhood_cleansed
Castro/Upper Market      13918586
Western Addition         13573392
Outer Sunset             13244787
Mission                  12045624
South of Market          10292836
Marina                    9902240
Bernal Heights            7692818
Outer Richmond            7545218
Downtown/Civic Center     7236257
Noe Valley                7191760
Name: estimated_revenue_l365d, dtype: Int64

2. Highest average revenue:
neighbourhood_cleansed
Presidio Heights            72138.0
Seacliff               63334.333333
Castro/Upper Market     58728.21097
Twin Peaks             50121.891892
Marina                 49020.990099
Visitacion Valley      47751.320755
Potrero Hill           46045.136364
Parkside                45461.83871
Inner Sunset           44983.244094
Outer Sunset               44149.29
Name: estimated_revenue_l365d, dtype: Float64

3. Highest-revenue property type:
property_type
Entire home                           48991390
Entire rental unit                    40430479
Entire guest suite                    24076008
Entire condo                          20491794
Private room in home                  16301853
Room in hotel                          9764165
Private room in rental unit            5580201
Private room in condo                  3636486
Entire guesthouse                      2711381
Entire townhouse                       2454672
Private room in guest suite            1734274
Room in boutique hotel                 1684259
Entire loft                            1405057
Entire villa                            929515
Entire serviced apartment               879926
Entire place                            861068
Room in aparthotel                      815809
Private room in townhouse               644768
Entire cottage                          551188
Entire resort                           321737
Private room in bed and breakfast       235437
Private room in guesthouse              218802
Entire bungalow                         155588
Private room                            154513
Private room in loft                    143159
Private room in hostel                   97548
Casa particular                          87338
Shared room in rental unit               83958
Shared room in hotel                     70755
Entire vacation home                     68768
Private room in cottage                  56249
Entire in-law                            56100
Private room in serviced apartment       52017
Room in hostel                           42496
Entire cabin                             41270
Tiny home                                40929
Shared room in hostel                    38672
Shared room in bed and breakfast         38505
Private room in resort                   20389
Shared room in condo                     19859
Shared room in boutique hotel            16065
Shared room in home                       8365
Campsite                                  6402
Private room in bungalow                     0
Private room in casa particular              0
Room in serviced apartment                   0
Room in bed and breakfast                    0
Private room in villa                        0
Shared room in loft                          0
Name: estimated_revenue_l365d, dtype: Int64

4. Highest average revenue by property type:
property_type
Entire place                               107633.5
Entire villa                          103279.444444
Casa particular                             87338.0
Entire home                            65234.873502
Entire townhouse                        59870.04878
Entire guest suite                     58014.477108
Entire in-law                               56100.0
Entire cottage                              55118.8
Entire bungalow                        51862.666667
Entire guesthouse                      47568.087719
Entire cabin                                41270.0
Entire loft                            39029.361111
Private room                               38628.25
Private room in guest suite            35393.346939
Entire condo                           31189.945205
Private room in condo                  29564.926829
Entire rental unit                     28755.674964
Room in aparthotel                     28131.344828
Shared room in rental unit                  27986.0
Private room in townhouse              26865.333333
Private room in guesthouse             24311.333333
Private room in loft                   23859.833333
Room in hostel                              21248.0
Private room in home                   21061.825581
Shared room in condo                        19859.0
Private room in cottage                18749.666667
Private room in hostel                      16258.0
Shared room in boutique hotel               16065.0
Room in boutique hotel                 15451.917431
Entire serviced apartment                   14914.0
Shared room in hotel                        14151.0
Tiny home                                   13643.0
Private room in rental unit            13577.131387
Shared room in bed and breakfast            12835.0
Room in hotel                          12039.660912
Private room in serviced apartment          10403.4
Entire resort                          10378.612903
Shared room in home                          8365.0
Private room in bed and breakfast       8118.517241
Shared room in hostel                        7734.4
Campsite                                     6402.0
Entire vacation home                    5730.666667
Private room in resort                     2548.625
Private room in casa particular                 0.0
Room in bed and breakfast                       0.0
Room in serviced apartment                      0.0
Shared room in loft                             0.0
Private room in bungalow                       <NA>
Private room in villa                          <NA>
Name: estimated_revenue_l365d, dtype: Float64

5. Discount:
Cannot answer — no discount column exists.

6. Unusually large listings:
          id                                               name    price  \
20     33578                        Potrero Hill Garden Lookout    531.0
63    137129                        San Francisco Luxury Rental   1425.5
150   607500           Newly Renovated - San Francisco in Style   1533.5
162   699723  Potrero Penthouse | 4 Sunny Decks + Skyline Views   1141.0
202   918341                        Potrero Hill Garden Getaway    531.0
212   982298                   The Surf Shack - 6 beds, hot tub  1276.33
223  1067031            Spacious 3BR/2BA home with easy parking    625.0
229  1098003                Lovely, Unique Home Near Everything   1010.0
249  1212746  Large 3BR SF Home! Families, Friends or Collea...   1697.0
251  1225969                       Million dollar Bay View home   850.33
258  1291092   Gorgeous Marina Home near the Golden Gate Bridge  2250.75
293  1506702    Cow Hollow 3BR Home • Deck + GG Views • Parking    941.0
315  1673011  Stunning Home above Dolores Park w/Sweeping Views    821.5
343  1907229      Refined Victorian Home in Prime City Location   1152.0
352  2026910         Sweet Edwardian NOPA 3Bd w/Views & Parking    943.0
383  2298930              Private Room in Large Cow Hollow Flat    932.0
405  2592518                         Total Gem Two Bedroom Home   499.33
411  2723005     Awesome Location, Great for Business Travelers   1261.0
414  2739477                                 Home in the Castro   960.67
480  3761446                         Amazing Large Central Flat    925.0

     estimated_revenue_l365d
20                    135405
63                    156805
150                   134948
162                   200816
202                   135405
212                   140396
223                   123750
229                   155540
249                   392007
251                   140304
258                   297099
293                   239955
315                   207840
343                   177408
352                   240465
383                   194788
405                   127329
411                   152581
414                   244971
480                   223850

7. Price vs revenue correlation:
                            price  estimated_revenue_l365d
price                    1.000000                 0.091433
estimated_revenue_l365d  0.091433                 1.000000

8. Strongest month:
month
6.0     180306
5.0     161308
4.0      22040
3.0      17748
2.0      10705
1.0       8551
12.0      7907
11.0      6173
8.0       5804
9.0       5382
10.0      4837
7.0       3341
Name: number_of_reviews, dtype: Int64

9. Highest-revenue room type:
room_type
Entire home/apt    145146583
Private room        38446134
Hotel room           2150318
Shared room           276179
Name: estimated_revenue_l365d, dtype: Int64

10. Data-quality issues:
bedrooms                       1991
bathrooms                      1926
beds                           1697
review_scores_location         1586
review_scores_checkin          1586
review_scores_value            1586
review_scores_cleanliness      1585
review_scores_accuracy         1585
review_scores_communication    1585
month                          1584
year                           1584
review_scores_rating           1584
reviews_per_month              1584
first_review                   1584
last_review                    1584
year_month                     1584
price_quote_price_per_night    1400
price_quote_total_price        1400
estimated_revenue_l365d        1400
price                          1400
dtype: int64